### ISSUE TITLE
Crash when I'm editing a list 

### ISSUE THREAD

**Issue by lascapi** [stefan-niedermann/nextcloud-notes#437] opened 2018-07-18 19:47 UTC
Hello, 
When I edit a list there is a bug. 

1. Add a list (bullet or number list)
2. Pass in view mode
3. Pass in edit mode 
4. Go on the last line press enter two time 
5. The application crash. 

I've this bug every time I try. I use LineageOS on a Nexus5 ! 

And there is a bug with bullet list, we should see "- " and we see "· - " it's not beautiful ! :-) 

Thank you :)

**Comment by stefan-niedermann** [comment] 2018-07-18 20:10
Thank you for the report. Since which version are you experiencing this issue?

**Comment by lascapi** [comment] 2018-07-18 20:15
I don't know. I'm using v0.18.0 from Fdroid. 
I think it's an old bug, maybe the start of 2018...

**Comment by KlausHuber** [comment] 2018-07-27 13:44
looks like it's a duplicate of #335

**Comment by stefan-niedermann** [comment] 2018-08-23 12:07
Yes, indeed, i will close this issue in favor of #335 :)

**Closed by stefan-niedermann** 2018-08-23 12:07 UTC
Labels: Duplicate
