### ISSUE TITLE
Lock workspace with pin (desired feature)

### ISSUE THREAD

**Issue by kebechsenuef** [stefan-niedermann/nextcloud-notes#617] opened 2019-12-02 20:03 UTC
It would be great, if i can protect the notes with a password/pin, if someone has access to the device.

**Comment by stefan-niedermann** [comment] 2019-12-02 21:59
Duplicate of #354 .

Current focus is on Multi-Account-Support and Single-Sign-On, the next important topic after this will be to enhance the markdown editor. So this issue will likely take some time to implement.

You can open a Pull Request, upvote the issue or put a bounty on it, if you need this feature urgently.

Thank you for your patience and kind regards

Stefan

**Closed by stefan-niedermann** 2019-12-02 21:59 UTC
Labels: Duplicate
