### ISSUE TITLE
Ability to share note with NC users from phone app

### ISSUE THREAD

**Issue by 05nelsonm** [stefan-niedermann/nextcloud-notes#506] opened 2018-12-03 19:52 UTC
Would be awesome if we could share a note with another user on our server, from the phone app. 

As it stands now I have to go into the nextcloud app and share the file with another user, but it doesn't dump it in the other user's note folder. If they dont go in and move the file into their note folder, edits to the note just creates a duplicate and breaks the share

**Comment by stefan-niedermann** [comment] 2018-12-04 14:23
Duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/231

**Closed by stefan-niedermann** 2018-12-04 14:23 UTC
Labels: Duplicate
