### ISSUE TITLE
When creating a note starting with "# Test", the "#" character is included in title/filename

### ISSUE THREAD

**Issue by falzonv** [stefan-niedermann/nextcloud-notes#1205] opened 2021-05-06 15:42 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

- When creating a note where the first line is a title like `# Test`, the markdown character `#` is included in the filename.
- The same is observed with `## Test`, the two `#` are present at the beginning of the filename.
- This bug appeared after upgrading to v3.4.1 (not sure of the exact previous version but it was at least v3.2.2).
- It may (or not) be related to the fix of #1104, since this was about markdown in the title and was implemented in v3.4.1.

**To Reproduce**

1. Create a new note
2. Write `# Test` on the first line
3. Move back to the list of all notes to save
4. The note now has the title `# Test`
5. Checking on the server, the file have been saved as `# Test.md` (didn't even know it was possible!)

**Expected behavior**

The title markdown character `#` and the space before text should be ignored for defining the title and filename.
In the example above, the title should be `Test` instead of `# Test` and the filename should be `Test.md` instead of `# Test.md`.

**Screenshots**

Not applicable.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 8.1
 - Device: Motorola G5 Plus

**Server**
 - Nextcloud version: 20.0.9
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**

Not applicable.

**Comment by AlpAcA0072** [comment] 2021-05-07 12:47
I've located the problem to the method [generateNoteExcerpt](https://github.com/stefan-niedermann/nextcloud-notes/blob/fa9a59aebaa277b2336e619f1a4c4f47cd3166a2/app/src/main/java/it/niedermann/owncloud/notes/shared/util/NoteUtil.java#L66), it seems that the method [removeMarkdown](https://github.com/stefan-niedermann/nextcloud-notes/blob/fa9a59aebaa277b2336e619f1a4c4f47cd3166a2/markdown/src/main/java/it/niedermann/android/markdown/MarkdownUtil.java#L478) with the functionality of removing the markdown syntax is not well implemented as mentioned in [issue#1104](https://github.com/stefan-niedermann/nextcloud-notes/issues/1104#issuecomment-816892217).
I think adding a check to the title to see if it starts with the `#` would solve the problem, would that work?

**Comment by stefan-niedermann** [comment] 2021-05-07 12:52
Yes, this will ne the short term solution. In the long term i plan to use something similar to what we do in [`MarkdownUtil#renderForRemoteView`](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/markdown/src/main/java/it/niedermann/android/markdown/MarkdownUtil.java#L70-#L74) to remove the markdown.

**Comment by AlpAcA0072** [comment] 2021-05-08 09:34
It seems that we may not migrate the [renderForRemoteView](https://github.com/stefan-niedermann/nextcloud-notes/blob/fa9a59aebaa277b2336e619f1a4c4f47cd3166a2/markdown/src/main/java/it/niedermann/android/markdown/MarkdownUtil.java#L69) cause we don't have the `context`. However, from the called method [MarkdownConfiguration](https://github.com/yydcdut/RxMarkdown/blob/4c1bc116096ef77834c824960a428eea03645d84/markdown-processor/src/main/java/com/yydcdut/markdown/MarkdownConfiguration.java#L316) we can see that the `context` is used to process the `Image`. Since there's not image in the title, we don't have to have `context`. Is there any possible solution for this problem?

**Comment by stefan-niedermann** [comment] 2021-05-10 07:03
I don't think we need the `Context`: In `renderForRemoteView` it is only needed for the last step, where the appearance of the `Spannables` is enhanced. For removing the markdown, we only need the previous steps (parsing the markdown and converting it to html, then using `HTMLCompat#fromHtml` to get thr `Spanned` content, then just calling `toString`).

**Comment by korelstar** [comment] 2021-05-12 12:22
Can't reproduce with version 3.4.1.

**Comment by stefan-niedermann** [comment] 2021-05-12 12:43
Yes i can. Creating a new note and typing `# Hello` shows the `#` character in the title of the note (after returning to the list or waiting for auto-save)

**Comment by korelstar** [comment] 2021-05-12 12:50
Ah, okay, it's about the missing new line at the end. Then please try to remove the `$` from the end of the `PATTERN_HEADINGS`. It should work without and this may fix the issue.

**Comment by korelstar** [comment] 2021-05-12 12:51
... and we should add a test for this special case.

**Comment by stefan-niedermann** [comment] 2021-05-12 12:57
Aah, got it! Thanks for the analysis. Removing the `$` should indeed be enough. Plus adding a test.

**Comment by stefan-niedermann** [comment] 2021-05-12 13:03
Nah, the existing test already explicitly tests a single line.

**Comment by stefan-niedermann** [comment] 2021-05-12 13:06
Hehehe, i suspect the problem to be here: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/shared/util/NoteUtil.java#L120

where `removeMarkdown(content)` instead of just `content` should be applied.

Last code change 2015 - i guess this behavior is there since the very beginning :smile:

**Comment by stefan-niedermann** [comment] 2021-05-12 13:24
Will be fixed in `v3.4.3`.

**Closed** 2021-05-12 13:24 UTC
Labels: Enhancement

**Comment by falzonv** [comment] 2021-05-12 17:17
Great, thank you very much! :-)

**Comment by falzonv** [comment] 2021-05-21 08:44
Hello,

For information I just installed v3.4.3 and can confirm it is fixed.
Thank you again!

Best regards.
