### ISSUE TITLE
Stretched icons in create activity

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#279] opened 2017-10-17 11:28 UTC
Can anyone confirm this?

![screenshot_20171017-132708](https://user-images.githubusercontent.com/4741199/31662533-049e6f4e-b33f-11e7-93d6-d5f36a082d92.png)

cc @korelstar

**Comment by dan0xii** [comment] 2017-10-17 11:31
Yes I get this too but not all the time. I have been trying to pin down the cause.

**Comment by korelstar** [comment] 2017-10-17 11:59
I can confirm this, too. But I wouldn't invest any time in a solution, since this activity should be removed after merging it with the Edit Activity.

We have an issue about the merging, somewhere, AFAIR. The intention was to profit from features like auto save, favorites, categories etc. also for new notes while reducing maintenance for two activities.

**Comment by stefan-niedermann** [comment] 2017-10-17 15:12
Well, a short-term 0.12.1 bugfix version would be appreciated (fdroid does not show the images either, this could go into it, too).
I'll check if i can find something, any hint is welcome :)

**Comment by stefan-niedermann** [comment] 2017-10-26 20:53
Seems to be a problem of the support lib in the usee version. 26.0.2 should bring a bugfix: https://developer.android.com/topic/libraries/support-library/revisions.html#26-0-2

Though i recently installed android studio v3 and i am still fighting with it, so i am currently not able to build with support libs in version 26.0.2.

**If** someone has time and can confirm this is fixed with 26.0.2 feel free to bump the versions and merge it directly into master (as a single commit would be nice, so we can release a bugfix version)

**Comment by korelstar** [comment] 2017-10-27 04:58
I can confirm that this is fixed in 26.0.2. But we have a problem with our dependency to cert4android: They also use the support library (currently 26.0.1) and it's only possible to use one common version of the libs in the whole project.

Therefore, I think we have to wait until cert4android updates it's dependencies. But maybe, a git professional find another way to solve this problem.

**Comment by korelstar** [comment] 2017-10-27 05:07
I asked the authors to update their libraries: https://forums.bitfire.at/topic/1597/please-update-support-libraries

**Closed** 2017-10-27 12:10 UTC
Labels: Bug

**Comment by stefan-niedermann** [comment] 2017-10-27 16:46
Great! v0.12.1 released.
