### ISSUE TITLE
IndexOutOfBoundsException in note containing external images

### ISSUE THREAD

**Issue by n1try** [stefan-niedermann/nextcloud-notes#772] opened 2020-03-25 18:27 UTC
```
App Version: 2.11.3
App Version Code: 2011003
Files App Version Code: 30110054

---

OS Version: 4.9.200-ge39531f0f61b-ab6120732(6138846)
OS API Level: 29
Device: blueline
Model (and Product): Pixel 3 (blueline)

---

java.lang.IndexOutOfBoundsException: replace (5 ... 96) ends beyond length 91
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:513)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
	at com.yydcdut.markdown.syntax.text.ImageSyntax.parse(ImageSyntax.java:153)
	at com.yydcdut.markdown.syntax.text.ImageSyntax.format(ImageSyntax.java:70)
	at com.yydcdut.markdown.syntax.text.TextSyntaxAdapter.format(TextSyntaxAdapter.java:70)
	at com.yydcdut.markdown.chain.MultiSyntaxChain.handleSyntax(MultiSyntaxChain.java:46)
	at com.yydcdut.markdown.chain.SyntaxMultiChains.handleSyntax(SyntaxMultiChains.java:53)
	at com.yydcdut.markdown.chain.SyntaxDoElseChain.handleSyntax(SyntaxDoElseChain.java:58)
	at com.yydcdut.markdown.chain.SyntaxDoElseChain.handleSyntax(SyntaxDoElseChain.java:58)
	at com.yydcdut.markdown.chain.SyntaxDoElseChain.handleSyntax(SyntaxDoElseChain.java:58)
	at com.yydcdut.markdown.chain.SyntaxChain.handleSyntax(SyntaxChain.java:49)
	at com.yydcdut.markdown.syntax.text.TextFactory.parseByLine(TextFactory.java:220)
	at com.yydcdut.markdown.syntax.text.TextFactory.parse(TextFactory.java:200)
	at com.yydcdut.markdown.MarkdownProcessor.parse(MarkdownProcessor.java:47)
	at it.niedermann.owncloud.notes.android.fragment.NotePreviewFragment.onActivityCreated(NotePreviewFragment.java:164)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

**Comment by stefan-niedermann** [comment] 2020-03-25 19:11
Hey,

can you please tell me more about the exact circumstates?

- Does this happen in Edit- or in Preview-mode?
- Does it happen reproducably every time?
- Please share a minimal `.txt` or `.md`-file with which the issue is reproducable
- Are you using the Play Store or the F-Droid version?

Thank you in advance

Stefan

**Comment by n1try** [comment] 2020-03-25 20:11
Sorry, here are a few more details.

* The problem occurs when switching from edit- to preview mode
* It happens every time with this one particular note
* I'm using the paid Play Store version

Here's the content of the note file, called `test.txt`:
```markdown
# Überschrift
![](https://www.lebensbaum.com/files/styles/greige_image_476x476/public/images/greiges/birke1.jpg?itok=DBZX_Xmf)
Bild 1

![](https://vignette2.wikia.nocookie.net/warrior-cats/images/6/65/Buchenblatt.png/revision/latest?cb=20160223150637&path-prefix=de)
Bild 2

```

**Comment by stefan-niedermann** [comment] 2020-03-25 21:07
Okay, as a workaround you can simply add a description to your images (even a space character will prevent the crash) until i was able to analyze and fix the actual issue.


Your example with the workaround would look like this:

```md
# Überschrift
![ ](https://www.lebensbaum.com/files/styles/greige_image_476x476/public/images/greiges/birke1.jpg?itok=DBZX_Xmf)
Bild 1

![ ](https://vignette2.wikia.nocookie.net/warrior-cats/images/6/65/Buchenblatt.png/revision/latest?cb=20160223150637&path-prefix=de)
Bild 2
```

Thank you for the report.

**Comment by stefan-niedermann** [comment] 2020-03-26 12:19
Will be fixed in `v2.11.5`.

**Closed by stefan-niedermann** 2020-03-26 12:19 UTC
Labels: Bug, Store :: Play Store, Upstream :: Markdown

**Comment by n1try** [comment] 2020-03-26 12:44
Thanks a lot!

**Comment by stefan-niedermann** [comment] 2020-03-26 12:49
Thank you for the report :wink:
