### ISSUE TITLE
problem witch nextcloud notes on android

### ISSUE THREAD

**Issue by sp6ina** [stefan-niedermann/nextcloud-notes#1138] opened 2021-04-13 08:12 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 20210402 (Beta)

---

OS Version: 4.14.116(11.0.0.178C432)
OS API Level: 29
Device: HWELS-P
Manufacturer: HUAWEI
Model (and Product): ELS-N39 (ELS-N39)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:929)

```

**To Reproduce**
1. Go to 'android app'
2. Click on 'login'
3. Scroll down to '…'

**Expected behavior**
I cant login to my instance of nextcloud

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: fdroid
 - Android-Version: 10
 - Device: huawei p40pro+

**Server**
 - Nextcloud version: newest
 - Nextcloud Notes version (server app): newest

**Stacktrace**

**Comment by JohnWalkerx** [comment] 2021-04-13 08:36
Duplicate of #1128

**Comment by stefan-niedermann** [comment] 2021-04-13 08:45
https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516

**Closed by stefan-niedermann** 2021-04-13 08:45 UTC
