### ISSUE TITLE
new feature request

### ISSUE THREAD

**Issue by MparkG** [stefan-niedermann/nextcloud-notes#565] opened 2019-07-15 17:38 UTC
Hey there,
Wouldnt it be nice to have the sharing feature of nextcloud implemented here?

Let me share a note via the app to someone else,
For editing, just viewing, watever.
of course let me see those notes in the app, which others share with me...

So with that id be wanting to have a note file on account A,
Which i edit on my phone through account A,
Which i share to account B.

Then person B with account B can use his Phone,
And view and edit the note, which A shared, on his phone, with this very Note app.

Such way both can manage and use this single centralized shared note.

Thanks

**Comment by stefan-niedermann** [comment] 2019-07-16 05:55
Yes, this would be nice. At first the server side app has to implement this feature, then the android app will follow. I think, there might be a duplicate issue already around here :)

**Comment by MparkG** [comment] 2019-07-16 07:23
Alles klar, dann bin ich gespannt.
Danke

Am 16. Juli 2019 07:55:37 MESZ schrieb Niedermann IT-Dienstleistungen <notifications@github.com>:
>Yes, this would be nice. At first the server side app has to implement
>this feature, then the android app will follow. I think, there might be
>a duplicate issue already around here :)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/stefan-niedermann/nextcloud-notes/issues/565#issuecomment-511676168

-- 
Max vom Telefon

**Comment by stefan-niedermann** [comment] 2019-07-19 07:03
Duplicate of #231 - let's continue discussion and work there :)

**Closed by stefan-niedermann** 2019-07-19 07:03 UTC
Labels: Duplicate
