### ISSUE TITLE
Markdown rendering of Lists

### ISSUE THREAD

**Issue by treborxy** [stefan-niedermann/nextcloud-notes#707] opened 2020-01-27 12:12 UTC
Using Notizen for Android v2.4.8 with lineageos 16.0 and samsung s7 herolte

- The rendering of unordered lists does not work correctly: no bullets, no indenting of following lines
- The rendering of numbered lists does not work correctly: while rendering, numbers are added to existing placeholders (e.g. first line "1." becomes "11.", second line "1." becomes "21."; no indenting of following lines

**Comment by stefan-niedermann** [comment] 2020-01-27 14:17
Please use the issue template and add screenshots and exact steps to reproduce (e.g. are you in preview- or in edit mode?).

Please provide the exact markdown you are entering (using for example pastebin or post a `.md`-file here).

**Comment by stefan-niedermann** [comment] 2020-02-03 09:46
Closing because of missing feedback.

Please reopen and provide the requested information.

**Comment by treborxy** [comment] 2020-02-03 12:04
@issue template: sorry, did not find (where is it?)
@screenshots: see below
@markdown sample: see below (extension renamed because of upload restriction, extension was .md)

Best Regards

![Screenshot_edit_Notizen](https://user-images.githubusercontent.com/19653937/73651602-09f70600-4685-11ea-9227-dee29496c225.png)
![Screenshot_view_Notizen](https://user-images.githubusercontent.com/19653937/73651603-09f70600-4685-11ea-94df-405bf360391a.png)

[Überschrift 1.txt](https://github.com/stefan-niedermann/nextcloud-notes/files/4147734/Uberschrift.1.txt)

**Comment by Filius-Patris** [comment] 2020-02-11 11:52
I also have these weird bullet points before the dashes in edit mode (in ULs). Is this intentional behavior?
Preview mode is completely fine though.

**Comment by stefan-niedermann** [comment] 2020-02-11 11:54
no, this is not by intention, it's a bug of the used rendering library. We think about replacing it (or fork and fix it)

**Comment by stefan-niedermann** [comment] 2020-02-25 19:24
It is nearly impossible to fix this behavior with the current library.

Therefore, closing this in favor of https://github.com/stefan-niedermann/nextcloud-notes/issues/549

I will have a look, that the rendering of lists will work better.

**Closed by stefan-niedermann** 2020-02-25 19:24 UTC
Labels: Bug, Upstream :: Markdown
