### ISSUE TITLE
Nextcloud notes app on the Meizu m5c

### ISSUE THREAD

**Issue by Ekibostos** [stefan-niedermann/nextcloud-notes#753] opened 2020-02-29 12:52 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server**
 - Nextcloud-Version: 
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: 

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: F-droid
 - Device: [e.g. Samsung Galaxy S10] Meizu m5c
 - Android-Version: [e.g. 8] 6

```
App Version: 2.10.3
App Version Code: 81
Files App Version Code: 30100190

---

OS Version: 3.18.19+(1554282576)
OS API Level: 23
Device: M5c
Model (and Product): M5c (meizu_M5c)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Api приложения Nextcloud files не отвечает. Пожалуйста, сообщите об этой проблеме.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:163)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:98)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:413)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:284)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```

**Comment by stefan-niedermann** [comment] 2020-02-29 12:55
Duplicate of #752 
Did you perform an update or a fresh install? If update: Which was the latest known version that worked?

**Comment by Ekibostos** [comment] 2020-02-29 13:17
It is a fresh install.
Nextcloud version 17.0.3
Nextcloud app from the F-droid works well

**Comment by stefan-niedermann** [comment] 2020-02-29 13:34
Thank you for reporting. You can watch #752 and https://github.com/nextcloud/Android-SingleSignOn/issues/162 to get notified about updates.

Have you tried to force stop both apps, then start the Nextcloud app and then start the Notes app?

> Nextcloud app from the F-droid works well

You mean the combination Notes (F-Droid) and Nextcloud (F-Droid) works well comparted to the combination Notes (F-Droid) and Nextcloud (Play Store)?

Or did you just mean that you have installed both from F-Droid and Nextcloud does work and Notes doesn't?

**Closed** 2020-03-04 11:57 UTC
Labels: Duplicate

**Comment by stefan-niedermann** [comment] 2020-05-01 04:06
See https://github.com/nextcloud/Android-SingleSignOn/issues/162#issuecomment-622194125
