### ISSUE TITLE
Crash when switching to View Mode

### ISSUE THREAD

**Issue by muchahagrande** [stefan-niedermann/nextcloud-notes#1056] opened 2021-01-31 17:34 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
When I open anote in edit mode I can work with it, but as soon as I switch to view mode, the app chashes.
It chashes also when I open the note in View Mode directly.

**To Reproduce**
1. Go to 'App'
2. Click on 'A note'
3. Switch to 'View mode'

**Expected behavior**
The note should be opened in View Mode

**Screenshots**

**Smartphone (please complete the following information):**

```
App Version: 3.1.1
App Version Code: 3001001
App Flavor: fdroid

Files App Version Code: 30140390

---

OS Version: 3.10.61-7557315(G903MUBS1BSB1)
OS API Level: 23
Device: s5neolte
Manufacturer: samsung
Model (and Product): SM-G903M (s5neolteub)


**Server**
 - Nextcloud version: 20.0.6
 - Nextcloud Notes version (server app): 3.5.1

**Stacktrace**
android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.MarkdownViewerImpl
 at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
 at it.niedermann.owncloud.notes.databinding.FragmentNotePreviewBinding.inflate(FragmentNotePreviewBinding.java:65)
 at it.niedermann.owncloud.notes.edit.NotePreviewFragment.onCreateView(NotePreviewFragment.java:77)
 at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
 at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
 at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
 at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
 at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
 at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
 at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
 at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:158)
 at android.app.ActivityThread.main(ActivityThread.java:7230)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.MarkdownViewerImpl
 at android.view.LayoutInflater.createView(LayoutInflater.java:657)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
 ... 22 more
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance(Native Method)
 at android.view.LayoutInflater.createView(LayoutInflater.java:631)
 ... 31 more
Caused by: java.lang.NoClassDefFoundError: it.niedermann.android.markdown.markwon.-$$Lambda$MarkwonMarkdownViewer$N0nQp3p98292jlHz07UHK8yKrAg
 at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.createMarkwonBuilder(MarkwonMarkdownViewer.java:89)
 at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:68)
 at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:63)
 at it.niedermann.android.markdown.MarkdownViewerImpl.<init>(MarkdownViewerImpl.java:18)
 ... 33 more
```

**Comment by stefan-niedermann** [comment] 2021-01-31 18:11
Related to https://github.com/stefan-niedermann/nextcloud-notes/issues/1042

**Comment by stefan-niedermann** [comment] 2021-01-31 18:14
Might be related to Syntax Highlighting according to the stacktrace

**Comment by LeSpocky** [comment] 2021-02-01 21:27
Not sure if view mode only. Here it crashes when trying to open any note:

```
App Version: 3.1.1
App Version Code: 3001001
App Flavor: fdroid

Files App Version Code: 30140190

---

OS Version: 3.10.49-gcc121dea994-00045-ge2e6e6dff33(WW_P024-V5.9.4-20170613)
OS API Level: 23
Device: P024_1
Manufacturer: asus
Model (and Product): P024 (WW_P024)

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.edit.EditNoteActivity}: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.MarkdownViewerImpl
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2440)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5484)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.MarkdownViewerImpl
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at it.niedermann.owncloud.notes.databinding.FragmentNotePreviewBinding.inflate(FragmentNotePreviewBinding.java:65)
	at it.niedermann.owncloud.notes.edit.NotePreviewFragment.onCreateView(NotePreviewFragment.java:77)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at it.niedermann.owncloud.notes.branding.BrandedActivity.onStart(BrandedActivity.java:34)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6340)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
	... 9 more
Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.MarkdownViewerImpl
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 32 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: it.niedermann.android.markdown.markwon.-$$Lambda$MarkwonMarkdownViewer$N0nQp3p98292jlHz07UHK8yKrAg
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.createMarkwonBuilder(MarkwonMarkdownViewer.java:89)
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:68)
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:63)
	at it.niedermann.android.markdown.MarkdownViewerImpl.<init>(MarkdownViewerImpl.java:18)
	... 43 more
```

Device is an older ASUS ZenPad (p024) with Android 6 and app installed from F-Droid.

**Comment by stefan-niedermann** [comment] 2021-02-01 22:18
> Not sure if view mode only. Here it crashes when trying to open any note

The error message still looks like view mode - Can you check your settings and see whether the display mode is set to "Always preview" or "Remember last"?

**Comment by LeSpocky** [comment] 2021-02-02 06:18
> > Not sure if view mode only. Here it crashes when trying to open any note
> 
> The error message still looks like view mode - Can you check your settings and see whether the display mode is set to "Always preview" or "Remember last"?

In German locale it reads:

> **Anzeigemodus für Notizen**
> Im Vorschaumodus öffnen

I can switch that to *Im Bearbeitungsmodus öffnen* and then I can edit notes again. If I hit the view button from inside the edit mode then, it crashes. If you need more information, let me know.

**Comment by domotic-29** [comment] 2021-02-02 15:54
Hello,

When I go to preview mode, it crashes with this error message:
```
App Version: 3.1.1
App Version Code: 3001001
App Flavor: fdroid

Files App Version Code: 30140190

---

OS Version: 3.14.27-986474(G361FXXU1APB1)
OS API Level: 22
Device: coreprimevelte
Manufacturer: samsung
Model (and Product): SM-G361F (coreprimeveltexx)

---

android.view.InflateException: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.MarkdownViewerImpl
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at it.niedermann.owncloud.notes.databinding.FragmentNotePreviewBinding.inflate(FragmentNotePreviewBinding.java:65)
	at it.niedermann.owncloud.notes.edit.NotePreviewFragment.onCreateView(NotePreviewFragment.java:77)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5910)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 28 more
Caused by: java.lang.NoClassDefFoundError: it.niedermann.android.markdown.markwon.-$$Lambda$MarkwonMarkdownViewer$N0nQp3p98292jlHz07UHK8yKrAg
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.createMarkwonBuilder(MarkwonMarkdownViewer.java:89)
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:68)
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:63)
	at it.niedermann.android.markdown.MarkdownViewerImpl.<init>(MarkdownViewerImpl.java:18)
	... 31 more

```

**Comment by stefan-niedermann** [comment] 2021-02-02 17:42
I found the root cause ([source](https://stackoverflow.com/a/44047349)) and was able to fix it.

The issue affected only old devices (< Android 7.0) and will be fixed in `v3.0.2`.

**Closed** 2021-02-02 17:44 UTC

**Comment by domotic-29** [comment] 2021-02-02 17:53
Thank you!

**Comment by domotic-29** [comment] 2021-02-13 13:58
I see the new package in the depot only now and installed it.

When we start directly in preview mode, it shows a blank screen.
We have to display it in "edit mode" and then switch to "preview mode" in order to see the text.

Should I start a new bug report or can you handle it from here?

**Comment by muchahagrande** [comment] 2021-02-14 19:32
The same for me. Now preview mode works but only when switchig from edit mode. If I open the note in preview mode, it shows blank.
