### ISSUE TITLE
Screen off events delete current note, even if previously saved

### ISSUE THREAD

**Issue by adx442** [stefan-niedermann/nextcloud-notes#309] opened 2017-12-20 17:31 UTC
Issue:  When creating or viewing a note (previously fully saved!), if the screen turns off, the note will be completely erased.   If you're using this for a shopping list, and your attention lapses, you'll lose your list.  This happens whether the note is in initial edit mode (though it claims saving during editing) or if you open an existing note that was previously saved.  Erased notes can be restored from the Nextcloud versioning system, so this is a positive overwrite event by Nextcloud Notes.

App Version: 0.12.1 (both systems)

Nextcloud version: 12.04

App Source: Play store. 

Systems tested on:  Samsung Galaxy Tab S3 Android 7.0 Nougat (stock), Google Pixel XL on Android 8.1 (Oreo).

Edit:  Changing the view setting in the app to "Preview" instead of "Edit mode" eliminates the problem, however, content should not be erased in Edit by a screen off event.

**Comment by korelstar** [comment] 2018-02-01 17:58
Maybe this bug is related to #301. Can you please check this?

**Comment by korelstar** [comment] 2018-02-05 11:20
Are you able to test build and install the current developer version from this git repository? It's likely that this bug is fixed there.

**Comment by adx442** [comment] 2018-02-05 14:37
Sorry, no, I don't have the setup currently to build and deploy APKs myself.  Just reporting bugs here because it was required in order to have them reported.  

Issue 301, by the way, appears to be the same end result, but mine does not involve screen rotation, just screen off.

**Comment by korelstar** [comment] 2018-02-14 21:04
App version 0.13.1 is now available on F-Droid. It would be interesting, if this issue appears on that version, too. I assume that it is fixed.

**Comment by stefan-niedermann** [comment] 2018-02-16 12:43
(Play Store version is currently rolling out staged.)

**Comment by stefan-niedermann** [comment] 2018-04-10 10:53
@adx442 the Play Store is rolled out for some weeks now. Can you please retest if the problem is still reproducable? I will close this issue for now - feel free to reopen if you are still experiencing the bug.

Regards

**Closed by stefan-niedermann** 2018-04-10 10:53 UTC
Labels: Bug
