### ISSUE TITLE
Single Note Widget should handle check list preview

### ISSUE THREAD

**Issue by Ornanovitch** [stefan-niedermann/nextcloud-notes#559] opened 2019-05-27 11:27 UTC
Hi,

As the single note widget is a preview tool, it perfectly handles the preview of title levels with "#", and bullets with "-" or "*", but it does not handles the preview of checkbox with "[ ]", while the preview in the app handles this. 
(Also, it would be the icing on the cake if a check list preview allowed to check or uncheck items directly on the widget, but I keep this idea for a future request :candy: )

Thx for your great work anyway !

A picture so that you can see what I mean : 
![Screenshot_20190527-130505_Evie](https://user-images.githubusercontent.com/34077099/58416828-2b7a0980-8083-11e9-96de-ce452b899eeb.jpg)

**Comment by stefan-niedermann** [comment] 2020-01-27 17:18
Short answer: It is not possible because Google / Android doesn't allow any other classes than `TextView` (and some irrelevant others) **including** descendants (like our `RxMarkdownTextView`.

Though i did some experiments with search & replace with checkbox emojis - which fails on older devices and some devices which simply do not allow each emoji.

On top of thoses problems, i didn't find a reliable way to detect if a special emoji is really supported.

There seems to be an `EmojiCompat`-library from android where one could have another look, but this seems to be a bit like an overkill for me.

However, the best idea yet for me seems to **replace the characters with an `ImageSpan`**, though i didn't test this yet. Basically this is like implementing some features of `RxMarkdown` ourself 🙁.

If someone else has another idea, feel free to post it or open a PR.

**Comment by KopfKrieg** [comment] 2021-01-17 14:47
> Short answer: It is not possible because Google / Android doesn't allow any other classes than `TextView` (and some irrelevant others) **including** descendants (like our `RxMarkdownTextView`.

Quick question: Recently RxMarkdown has been replaced by Markwon, but the issue is still the same, right?

> Though i did some experiments with search & replace with checkbox emojis - which fails on older devices and some devices which simply do not allow each emoji.

The ["ballot box" characters are part of Unicode 1.1 from 1993](https://www.compart.com/en/unicode/search?q=Ballot+Box#characters), and [Android 1.5 ships with Unicode 5.0](https://developer.android.com/guide/topics/resources/internationalization).

To me it seems like replacing the checklist items with the unicode "ballot box" characters should be working on all Android devices.

**Comment by stefan-niedermann** [comment] 2021-01-17 16:03
> Quick question: Recently RxMarkdown has been replaced by Markwon, but the issue is still the same, right?

- The widgets are still using `RxMarkdown` (See ¹ for technical details)
- The situation won't change when the widgets would use `Markwon` instead of `RxMarkdown`

> The "ballot box" characters are part of Unicode 1.1 from 1993, and Android 1.5 ships with Unicode 5.0.

I tried it with an emulated Android 4.4 device which didn't work, though, i didn't use `ballot box` but another character. However another issue is that each damn manufacturer brings its own set of emojis, sometime all are supported, sometimes not. While this solution would make the looking a bit nicer, it is a dead end, because we will never be able to implement toggling by clicking on a checkbox this way. 

¹ Widgets on Android aren't executed and rendered by the apps but by the launcher. Therefore they need a common fixed set of features which are supported by both, app developers and launcher developers. One can not use subclasses of `TextView` for example, but only `TextView` itself, because the launcher code won't know anything about custom subclasses.
This is the whole pain and limitation. Shame on you Google. So, we can only use `TextView` which is only capable of rendering the type of `Spans` which it knows, like a `ForegroundColorSpan` for example. While `RxMarkdown` uses pretty much of those predefined `Spans`, `Markwon` doesn't, because they rely on a more abstract model and have custom `Span` implementations (which we could change via a plugin).

But here is another suggestion about how this could be implemented (And i think this will be the way to go):

The Single Note widget is already a "List widget with a single entry" to enable scrolling (Because not even a `ScrollView` does to the previously mentioned common fixed set of features).
If anyone wants to pick up this issue: My latest thoughts about this were to split up notes with checkboxes to different views and place them below each other in this list view. So a user shouldn't notice that he is technically dealing with multiple widgets, but we can add click listener for each single checkbox and nice images and so on.

```
__________
|        |
__________
|        |
__________
|        |
__________
```

This is not trivial though, because we never know perfectly when something **is** a checkbox and when not. Just consider a checkbox sample in a codeblock, so basically this:

````
How to make a checkbox:
```
- [ ] Item
```
````

**Comment by KopfKrieg** [comment] 2021-01-20 19:34
> While this solution would make the looking a bit nicer, it is a dead end, because we will never be able to implement toggling by clicking on a checkbox this way.

In the notes app it would be nice to be able to toggle the checkbox, but for the widget I'd be fine with only showing the checkbox. I mean, the widget isn't really interactive anyway, isn't it? It's there to get a quick overview of the note, and you can scroll it, but a click on it opens the note in the app, where you can use any TextView-Implementation you want, right?

**Comment by stefan-niedermann** [comment] 2021-01-20 19:48
> In the notes app it would be nice to be able to toggle the checkbox

This is possible in the view mode since years. If you mean the edit mode: This is not that easy as one might think, because we interfer with all Android mechanisms like text selection and so on. But this is off topic.

> I mean, the widget isn't really interactive anyway, isn't it?

You are right, but why not aim to make it more interactive? That's what this issue is for 😉. The way you described is one step more for a user and it might throw out a user of context because the whole screen changes.

**Comment by KopfKrieg** [comment] 2021-01-23 16:57
> You are right, but why not aim to make it more interactive? That's what this issue is for

Ah, sorry, I thought the issue is more about the appearance and less about interactive functions.

Regarding the previously posted idea:

> Though i did some experiments with search & replace with checkbox emojis - which fails on older devices and some devices which simply do not allow each emoji.

I now know you have different plans for the future, but in the meantime, would it be okay for you to take up this idea again? But this time with the ballot box character mentioned above, maybe - if you fear it will break things - in a new widget?

Or would you be open for a PR that implements this? I can't promise anything, the last time I've touched the source code of an android app was years ago, but I'd be willing to try it.

**Comment by stefan-niedermann** [comment] 2021-01-23 17:07
Sure, Pull Requests are welcome :)

We can replace the stuff with emojis for the visual appearance in the first place - no need for a new widget.

Just make sure, it doesn't break if the emojis are not supported 🚀

**Comment by stefan-niedermann** [comment] 2021-03-07 18:57
I implemented the emoji replacements (requires Android 6.0 or higher). For screenshots see https://github.com/stefan-niedermann/nextcloud-notes/pull/1078

The changes will be part of `v3.2.0`.

Toggling the checkboxes from within the widget directly is out of scope - there is simply no straight-forward API in Android and until there is no better way than the [crippled weird idea i had above](https://github.com/stefan-niedermann/nextcloud-notes/issues/559#issuecomment-761835517) i can and will not implement it.

As soon as there is a clean way or a someone has a better idea, just let me know here and we will analyze it again :)

**Closed by stefan-niedermann** 2021-03-07 18:57 UTC
Labels: Enhancement, Widget :: Single Note

**Comment by KopfKrieg** [comment] 2021-03-07 20:03
Seems like I can close my not working fork^^

Thank you very much for implementing it!
