### ISSUE TITLE
Unable to connect to Nextcloud server

### ISSUE THREAD

**Issue by beccon4** [stefan-niedermann/nextcloud-notes#593] opened 2019-10-01 14:51 UTC
After downloading the Nextcloud Notes app I entered the server address and its credentials but could not connect. Instead I get the following error message

`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;
at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
at at.bitfire.cert4android.TrustCertificateActivity.onCreate(TrustCertificateActivity.kt:46)
at android.app.Activity.performCreate(Activity.java:7140)
at android.app.Activity.performCreate(Activity.java:7131)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6692)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.databinding.DataBinderMapperImpl" on path: DexPathList[[zip file "/data/app/it.niedermann.owncloud.notes-kLHaSc5j7_bs_Fpdjh4qxQ==/base.apk"],nativeLibraryDirectories=[/data/app/it.niedermann.owncloud.notes-kLHaSc5j7_bs_Fpdjh4qxQ==/lib/arm64, /data/app/it.niedermann.owncloud.notes-kLHaSc5j7_bs_Fpdjh4qxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 18 more`

Device: Asus Zenfone ASUS_X00TD Build PKW1.WW_Phone-1.6_2017.1908.058-20190903
Nextcloud version: 16.0.5
Two Factor OAuth 2.0 in service.

The same app (version) works just fine with the same server on my other device, an rather old Lenovo Yoga 8 tablet.

**Comment by stefan-niedermann** [comment] 2019-10-01 17:23
Yes, i think this is a duplicate of #591

As a workaround, you can install the version before 0.27.1 and login. After that you should be able to update the android app version.

**Closed by stefan-niedermann** 2019-10-01 17:23 UTC
