### ISSUE TITLE
inconsistency in rendering of check boxes

### ISSUE THREAD

**Issue by o8k57** [stefan-niedermann/nextcloud-notes#878] opened 2020-06-17 10:28 UTC
In lists of check boxes, the size of the boxes is not consistent.

Example shown, with the associated markdown, in attached screenshots

![1 - Screenshot_20200617-111644_Nextcloud_Notes](https://user-images.githubusercontent.com/19149667/84887337-80712f00-b08d-11ea-8bca-1aad63fcaf3c.png)

![2 - Screenshot_20200617-111912_Nextcloud_Notes](https://user-images.githubusercontent.com/19149667/84887358-849d4c80-b08d-11ea-80fd-8a21c3828d09.png)

**Comment by stefan-niedermann** [comment] 2020-06-17 10:32
Thank you for the report. Yep, i am aware of it.

Please see here: https://github.com/stefan-niedermann/nextcloud-notes/issues/654#issuecomment-581077044

Closing this as duplicate of #654

**Closed by stefan-niedermann** 2020-06-17 10:32 UTC
