### ISSUE TITLE
Confirm before deletion

### ISSUE THREAD

**Issue by enoch85** [stefan-niedermann/nextcloud-notes#310] opened 2017-12-23 19:57 UTC
A user just called me and was very frustrated because she accentually swiped left and removed a note containing ALL here passwords. The strange thing is that it didn't end up in the trashbin so I couldn't even restore it. Luckily I had a backup and we could revert the note from there, but still, I think it's WAY to easy to delete a note, as you don't even get a confirmation.

So, I suggest that you should add a confirmation when removing a note. Something like a popup asking "Are you sure?" or similar.

Please add this, it's important that notes don't get accentually deleted. Thank you!

cc @stefan-niedermann

**Comment by stefan-niedermann** [comment] 2018-02-04 20:05
Hi,

> The strange thing is that it didn't end up in the trashbin so I couldn't even restore it.

This is definitely a strange behavior. Can you reproduce this? A deleted note should be restoreable from trashbin.

I think, confirm-dialogs are a bad experience, since users are trained to click "ok"-buttons at each dialog. The app provides an Undo-Toast, why didn't the user use it? Didn't it work or was too little time to undo before the toast disappeared?

**Comment by enoch85** [comment] 2018-02-04 20:45
> why didn't the user use it?

The user is over 60 years old, and didn't notice the undo-toast. It should be user friendly for all ages, not just young people and tech-savvy folks.

Sorry, I can't reproduce it.

**Comment by stefan-niedermann** [comment] 2018-02-06 14:36
Okay, i have a strong opinion here, but let's get some further input! :)

@nextcloud/designers **Beside the problem, that the note did not land in the trashbin, as it definitely should have**: Please Up-Vote for Undo, Down-Vote for confirm-dialog

**Comment by enoch85** [comment] 2018-02-06 16:00
@stefan-niedermann Both would be nice.

In this specific case the note contained all her passwords, and I got a call late at night with someone more or less screaming "where are my passwords??!?!?!" You can blame the end user, that's the easiest, but in this case we/you could actually do something about it. :)

**Comment by korelstar** [comment] 2018-02-06 16:08
@enoch85 Did you figured out, why the note wasn't in the trash bin? Is the nextcloud app "Deleted files" activated?

I still like the idea of integrating the server side trash bin into the Android app.

**Comment by enoch85** [comment] 2018-02-06 16:21
@korelstar I have no clue. The trashbin was the first place I checked, but nothing there. 

Also, this was some time ago so I don't have any logs.

**Comment by dan0xii** [comment] 2018-02-06 16:43
> I think, confirm-dialogs are a bad experience, since users are trained to click "ok"-buttons at each dialog. The app provides an Undo-Toast, why didn't the user use it? Didn't it work or was too little time to undo before the toast disappeared?

Would a solution be to prompt the user to swipe to delete as @enoch85 suggests but make the dialog options "Delete" or "Cancel" and use a tick box to allow the user to suppress future warnings. Once this is ticked and the user swipes to delete a note they won't see a dialog, just the "Undo" toast. The tick box value could be stored in the settings should the user want to re-enable the dialog.

**Comment by stefan-niedermann** [comment] 2018-02-06 17:19
> You can blame the end user

Hell, no! 😆 I wouldn't dare!

But the problem is, the app did not work as expected (note was not in trashbin), so this is definitely our fault.
So we have two topics here: confirm vs undo and why-was-the-note-not-in-the-trashbin. While the one is a opinion based choice, the other one is clearly a bug.

> Sorry, I can't reproduce it.

And that's a pity, because we have no clue how we can fix this bug.

What leads us back to the first topic.

A prompt like @dan0xii suggested might be a compromise (though i still would prefer to not have confirm-dialogs at all in the app). What do you think @enoch85 ?

**Comment by enoch85** [comment] 2018-02-06 18:03
I think @dan0xii's solution is the best of two worlds. The end goal here is to not delete notes by accident, and for tech-savvy or younger people they could just tick the box. Older people and less tech-savvy would have to actually press delete, and also confirm to not show the warning again. 

I'd say if we implement this and she calls me again, I'd blame her. ;)

What do you think @stefan-niedermann?

**Comment by dtcg** [comment] 2018-03-02 16:28
I also find the swipe-to-delete option somewhat dangerous :)

How about a swipe behaviour configuration in the settings? The user would have to choose what happens on swiping action, for instance: delete / do nothing / open in edit mode / etc.

No more confirm-dialogs, trashed or vanished notes.

**Comment by stefan-niedermann** [comment] 2018-03-02 23:22
There was a suggestion in another issue to use swipe-from-left-to-right for marking as favorite. That sounded pretty nice, maybe this could be an improvement since it reduces the risk to delete by 50%?

**Comment by enoch85** [comment] 2018-03-03 13:57
I don't remember which app that used it in the past (maybe ownCloud iOS) but when you swiped to the right an icon was shown (red trash can) and when you pressed it the file got deleted. That would be the best implementation I think.

Something like this:

![swipe_listview_item](https://user-images.githubusercontent.com/4511254/36935101-2cbf3506-1ef3-11e8-96a4-999adc2ed12f.gif)

**Comment by brianekummer** [comment] 2018-03-15 15:30
Another option to prevent accidental deletion (which I agree is an issue, and it has bitten me in the past) could be the option of "locking" specific notes to prevent deletion. On the edit screen, add a locked/unlocked icon that could be toggled like the favorite icon.

**Comment by stefan-niedermann** [comment] 2018-04-10 15:18
I implemented ["swiping from left to right -> marks favorite"](https://github.com/stefan-niedermann/nextcloud-notes/issues/310#issuecomment-370085361) on this branch:
https://github.com/stefan-niedermann/nextcloud-notes/tree/310-swipe-left-favorite

Open question: swiping from left: background should be yellow, swiping from right: background should be red.

Anyone who is interested can checkout this branch and give feedback.

**Comment by stefan-niedermann** [comment] 2018-04-10 16:51
huh? @enoch85 you even upvoted my comment :laughing: https://github.com/stefan-niedermann/nextcloud-notes/issues/310#issuecomment-370085361

**Comment by enoch85** [comment] 2018-04-10 18:37
@stefan-niedermann Yeah, beacuse I thought you would add that *and* deletion confirmation. But, let's see how this turns out. :)

**Comment by enoch85** [comment] 2018-04-12 14:46
@stefan-niedermann The user in question was my mom which is 60+, so with that in mind maybe a undo confirmation wouldn't be s bad after all? ;)

1. Even if it's 7 seconds it's still quite small.
2. This app is not only for tech-savvy people or people that knows how "standard" logic works.

**Comment by stefan-niedermann** [comment] 2018-08-24 08:47
Sorry @enoch85 but there will definitely no confirmation before deletion. We can always think about other options to make the app less destructive (e. g. a direct trashbin integration is planned, to easily restore deleted notes from within the app itself), but i think confirmation dialogs are learned behavior in sense of "oh, a pop-up - quick! press OK!".

**Closed by stefan-niedermann** 2018-08-24 08:47 UTC
Labels: Discussion, UX
