### ISSUE TITLE
Search function shows results only after restarting screen

### ISSUE THREAD

**Issue by danjde** [stefan-niedermann/nextcloud-notes#424] opened 2018-06-26 16:37 UTC
Hi Friends!
I know that this issues seems very funny, but it's real!
I'm using "CyanogenMod 12.1-20150518-UNOFFICIAL-s3ve3g" (without GAPS) on Samsung GT-I9301I,
if I perform a term search, something moves quickly, but then all the notes appear on the screen. I just wait 30 seconds (the timeout time of the display) and at the display resuming appears the list of files correctly filtered by the search term.
Same behavior manually locking and unlocking the display.

UPDATE:
this behavior only from global view, and with 1908 notes/txt.

I don't aspect a solution for me around this issue, only notify you.
If you want more info tell me.

I will certainly be updating the firmware in a few months and I will let you know around this issue..

Many thanks!

Davide

**Comment by stefan-niedermann** [comment] 2018-08-23 12:16
Dead @danjde,

thank you for reporting this problem. Did you update your firmware in the last few months? Are you still able to reproduce this problem with the very latest version of the app?

**Comment by stefan-niedermann** [comment] 2018-08-26 11:46
Sorry, i can't reproduce your issue. Maybe you can make a short screen recording video or gif to show us the behaviour? I will close this issue for now, just reopen if youve got some news :)

**Closed by stefan-niedermann** 2018-08-26 11:46 UTC
