### ISSUE TITLE
Hide password in settings until changed

### ISSUE THREAD

**Issue by livier** [stefan-niedermann/nextcloud-notes#162] opened 2017-01-17 16:16 UTC
I realised that when I came back to setup page (Paramètres in french)  I can click on the Eye symbol and see my nextcloud password. 
No much people have access to my device, but I don't like they should have access so easily to my clear passwd.
Should the connexion be provide by nextcloud account when available. Not sure android is very secure, but a bit less easy to access I hope.

**Comment by korelstar** [comment] 2017-01-18 15:06
Interesting aspect. We could empty the password field and only update the saved password if a new one was entered.

**Comment by stefan-niedermann** [comment] 2017-01-19 08:16
Jup, thought about android handles wlan settings. 

(In english it says: Not changed... until you enter another password)


![tmp_5265-img_20170119_091543-1645855574](https://cloud.githubusercontent.com/assets/4741199/22098667/eb384bf2-de27-11e6-86d0-908756effe07.jpg)

**Comment by stefan-niedermann** [comment] 2017-03-21 10:22
> I can click on the Eye symbol and see my nextcloud password.

I don't have an eye-icon in the password field. Maybe this is manufacturer specific? What device are you using with what OS-version?

**Comment by korelstar** [comment] 2017-03-23 20:17
Strange. I had definitely the eye-icon, too. However, it's gone now. Unfortunately, I can't remember where I've seen the icon (emulator or real phone). Maybe, there was a change in a library we use (and I've updated them multiple times). But I think, we should nevertheless change the behavior as discussed above.

**Comment by stefan-niedermann** [comment] 2017-03-23 21:33
@korelstar i had just v0.9.0 installed and i can confirm that there was the eye symbol. i think one of the updated support libs is the reason...

> The TextInputLayout password toggle is now disabled by default to avoid unnecessarily overwriting developer-specified end drawables. It may be manually enabled via the passwordToggleEnabled XML attribute.

([source](https://developer.android.com/topic/libraries/support-library/revisions.html))

> But I think, we should nevertheless change the behavior as discussed above.

I agree, but when there is no eye, no information except the length of the password is "leaked". Therefore this issue has no priority for me anymore. Though i accept Pull Requests, of course.

**Comment by livier** [comment] 2017-03-23 23:01
To answer the question :+1: 
Note version 0.9.0
Android 4.0.4
device Samsung GT-S7560M
I know, all the device could semm to you a bit outdated
But for ecological, social, and money reasons, I prefer to keep it for  long tinme more If possible.

I do not know how to take the eye off, so the problem is still here for me.
Should accept a workarround if no correction is sheduled in a short time.
I'm linux user, but never do anythin on android device, so details welcome for the workaround.
Thanks

**Comment by stefan-niedermann** [comment] 2017-03-24 06:54
@livier **The problem will be fixed for you in the next version** (v0.10.0).

This version is already tagged and will be available on F-Droid within the next view days.
If you are using the App from Google Play Store you will habe to be a bit more patient since i am doing a staged roll out there.

**Closed** 2017-04-24 19:50 UTC
Labels: Enhancement
