### ISSUE TITLE
Sinc failed

### ISSUE THREAD

**Issue by ivanra78** [stefan-niedermann/nextcloud-notes#1304] opened 2021-07-25 08:18 UTC
```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30160190

---

OS Version: 4.9.227-perf-g5de92d1(V12.5.1.0.RFBEUXM)
OS API Level: 30
Device: grus
Manufacturer: Xiaomi
Model (and Product): Mi 9 SE (grus_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: No se ha encontrado la cuenta en la app de Archivos de Nextcloud
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.main.MainViewModel.lambda$synchronizeCapabilities$13$MainViewModel(MainViewModel.java:406)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainViewModel$Kr1O01KODRuj8fCWyoVh0ZkuW9I.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by ivanra78** [comment] 2021-07-25 08:22
Hi, I'll hope the information'll be enough to explain the bug. Thanks.
The notes app doesn't sincronize. If you need more info, please, contact me.

**Comment by stefan-niedermann** [comment] 2021-07-25 11:28
Please see https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#nextcloudfilesappaccountnotfoundexception

Closing as duplicate of #1295

**Closed by stefan-niedermann** 2021-07-25 11:28 UTC

**Comment by ivanra78** [comment] 2021-07-25 15:05
Tranks!!
