### ISSUE TITLE
Checkbox does not show on Widget

### ISSUE THREAD

**Issue by Dennis-Bezold** [stefan-niedermann/nextcloud-notes#1052] opened 2021-01-25 06:54 UTC
**Describe the bug**

Note widget isn't showing a defined checkbox.

**To Reproduce**
1. Add a checkbox to a note
2. Add a Widget to the start menu
3. Add the note to the widget

**Expected behavior**

Something like this
![image](https://user-images.githubusercontent.com/12915325/105671146-844a1700-5ee2-11eb-829f-a17103674bdd.png)

**Screenshots**
Error looks like this

![image](https://user-images.githubusercontent.com/12915325/105671097-71374700-5ee2-11eb-818d-268327386630.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): v3.1.0
 - F-Droid or Play Store: Play Store
 - Android-Version: 10
 - Device: Fairphone 2

**Server**
 - Nextcloud version: Nextcloud 20.0.5
 - Nextcloud Notes version (server app): 4.0.2

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2021-01-25 06:58
Please use the search function before opening new issues.

Duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/559.

**Closed by stefan-niedermann** 2021-01-25 06:58 UTC
