### ISSUE TITLE
Application failed after I put a favorite star on a note

### ISSUE THREAD

**Issue by selivan** [stefan-niedermann/nextcloud-notes#1107] opened 2021-03-25 14:31 UTC
**Describe the bug**

Application failed after I put a favorite star on a note.

**To Reproduce**

Can not reproduce, failed once. See the stacktrace

**Smartphone (please complete the following information):**

 - Nextcloud Notes-Version (android app): 3.2.3
 - F-Droid or Play Store: F-Droid
 - Android-Version: 10
 - Device: Xiaomi Redmi Note 8T

**Server**
 - Nextcloud version: 18.0.14
 - Nextcloud Notes version (server app): 3.6.4

**Stacktrace**

```
App Version: 3.2.3
App Version Code: 3002003
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.117-perf-g847c8aa(V12.0.3.0.QCXRUXM)
OS API Level: 29
Device: willow
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8T (willow_ru)

---

java.lang.ClassCastException: it.niedermann.owncloud.notes.main.items.section.SectionItem cannot be cast to it.niedermann.owncloud.notes.shared.model.DBNote
 at it.niedermann.owncloud.notes.main.MainActivity.onNoteClick(MainActivity.java:865)
 at it.niedermann.owncloud.notes.main.items.NoteViewHolder.lambda$bind$0$NoteViewHolder(NoteViewHolder.java:54)
 at it.niedermann.owncloud.notes.main.items.-$$Lambda$NoteViewHolder$gRMMnB3AB9zSxSbpOevtjW6t0zE.onClick(Unknown Source:2)
 at android.view.View.performClick(View.java:7297)
 at android.view.View.performClickInternal(View.java:7274)
 at android.view.View.access$3600(View.java:819)
 at android.view.View$PerformClick.run(View.java:28017)
 at android.os.Handler.handleCallback(Handler.java:914)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:225)
 at android.app.ActivityThread.main(ActivityThread.java:7564)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by stefan-niedermann** [comment] 2021-03-25 14:57
Did you mark it as favorite by clicking on the :star: or by swiping from left to right?

**Comment by selivan** [comment] 2021-03-25 15:51
@stefan-niedermann By clicking on the :star: 

If I remember right: I clicked on a :star: , note I clicked on doubled in two: one with star and one without. I clicked on one of them, and the app crashed. Not sure how exactly it happened, it was 1 time only.

**Comment by stefan-niedermann** [comment] 2021-03-25 16:16
Yep, i thought so. It's a duplicate of #1023 - the old item in the list doesn't vanish and clicking on it will cause a not reliable state.
Thanks for the report, though!

**Closed by stefan-niedermann** 2021-03-25 16:16 UTC
