### ISSUE TITLE
Images not showing in preview

### ISSUE THREAD

**Issue by fcwoknhenuxdfiyv** [stefan-niedermann/nextcloud-notes#1229] opened 2021-05-21 13:32 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Images do not show when a note is in preview mode

**To Reproduce**
1. Create a note with an image url
2. Click on the preview icon

**Expected behavior**

Being a preview and all, the app should show the images.

I have added the images using the public sharing url of the server:

```
![bird -fullwidth](https://my.server/s/CWy7mEeJc3P5WAP/preview)
```

The image shows up fine in web browsers on the desktop and mobile firefox.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): v3.4.3
 - F-Droid or Play Store: F-Droid
 - Android-Version: 10
 - Device: Redmi Note 8

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 4.0.4

Thanks!

**Comment by stefan-niedermann** [comment] 2021-05-21 14:17
Yes, images from your Nextcloud instance are not yet supported because requesting them requires an authentication.

This issue will be fixed once #1018 has been implemented - you should subscribe to this issue to get notified about changes 😉

**Closed by stefan-niedermann** 2021-05-21 14:17 UTC

**Comment by fcwoknhenuxdfiyv** [comment] 2021-05-21 14:27
Hello Stefan!

The URL is a public one. I can curl it, so there is no authentication involved.
 
If I add this link, it doesn't work either:

```
![google](https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)
```

**Comment by stefan-niedermann** [comment] 2021-05-21 14:39
This URL works pretty well...?

**Edit mode:**

![Screenshot_20210521-163754_Nextcloud_Notizen](https://user-images.githubusercontent.com/4741199/119154924-ee1e9b80-ba52-11eb-9d5a-3fc1d2f990b2.png)

**Preview mode:**
![Screenshot_20210521-163807_Nextcloud_Notizen](https://user-images.githubusercontent.com/4741199/119154940-f1b22280-ba52-11eb-8899-c856ab444905.png)

**Comment by fcwoknhenuxdfiyv** [comment] 2021-05-21 14:41
Unfortunately, not on my phone :-(

Is there any debug output that I can supply?

**Comment by stefan-niedermann** [comment] 2021-05-21 14:43
Unfortunately not - you'll have to set up Android Studio and run it in an emulator. Probably it's related to infrastructure - dumb question, but you have a reliable network connection? Have you tried on Wi-Fi and mobile data?

**Comment by fcwoknhenuxdfiyv** [comment] 2021-05-21 15:21
My connection is reliable.

I'm starting to suspect that it has something to do with my phone being deGoogled.

**Comment by fcwoknhenuxdfiyv** [comment] 2021-05-21 15:29
It works from within the Nextcloud app.

**Comment by stefan-niedermann** [comment] 2021-05-21 15:30
I doubt that... i do not have any Play Services on my device either 😄 

However, `HttpURLConnection` was never very reliable at all (it is missing various features like retrys and has a broad list of issues regarding server and network configurations).

Unfortunately there is not much i can do if i am not able to reproduce it. Can you try it on another phone for testing purposes? (Family & friends)

Otherwise we won't have much choices except waiting for the Glide issue, which should solve the problem implicitly (also it is not related to an image which is hosted on NC)...

**Comment by fcwoknhenuxdfiyv** [comment] 2021-05-21 15:39
Okay.

Thanks for your time Stefan.

**Comment by stefan-niedermann** [comment] 2021-05-21 15:42
You're welcome, and sorry that i couldn't help you more 👋

**Comment by pythonmanGo** [comment] 2024-04-17 09:26
> Unfortunately, not on my phone :-(不幸的是，我的手机上没有:-(
> 
> Is there any debug output that I can supply?我可以提供任何调试输出吗？

I face  the same  question  in  xiaomi.would  you tell me how to  insert image and make image show.
