### ISSUE TITLE
Synchronization fails - account not found

### ISSUE THREAD

**Issue by squintarelli** [stefan-niedermann/nextcloud-notes#1295] opened 2021-07-19 07:07 UTC
**Describe the bug**
The app reports not finding the account in the files app, although it is there

**To Reproduce**
1. Modify a note
2. sync
Please notice I have two accounts setup in the files app and one in the notes app

**Expected behavior**
Sync working

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.11
 - F-Droid or Play Store: fdroid
 - Android-Version: 7.1.2
 - Device: Samsung sm-g935f
-  Nextcloud files app version: 3.16

**Server**
 - Nextcloud version: 21 
 - Nextcloud Notes version (server app): latest in nextcloud app store

**Stacktrace**
```
App Version: 3.4.3
App Version Code: 3004003
App Flavor: fdroid

Files App Version Code: 30160090

---

OS Version: 3.18.14-g1b5fc11fcdb(524b627a72)
OS API Level: 25
Device: hero2lte
Manufacturer: samsung
Model (and Product): SM-G935F (lineage_hero2lte)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: L'account non è stato trovato nell'applicazione File di Nextcloud
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:134)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)


java.lang.Exception: com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: L'account non è stato trovato nell'applicazione File di Nextcloud
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:134)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: L'account non è stato trovato nell'applicazione File di Nextcloud
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:205)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: L'account non è stato trovato nell'applicazione File di Nextcloud
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(lambda)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment] 2021-07-19 09:00
Have you tried to remove your account from the Notes app and add it again?

**Comment by squintarelli** [comment] 2021-07-19 09:05
yes.
I deleted the second account in Files app, then deleted the notes app and reinstalled
I had some timeout problems logging in.
Did some optimization on my server and the app works again
maybe it was due to a combination of factors

**Comment by stefan-niedermann** [comment] 2021-07-19 09:33
I am concerning that there might actually a bug because [two more people reported this issue](https://github.com/stefan-niedermann/nextcloud-notes/issues/1256) (on a different part of the app though).

So it is working properly again after the clean installation? Did you have this issue in the past more often or was this the first time?

**Comment by squintarelli** [comment] 2021-07-19 13:21
actually it's a copule of weeks I've had this issue, now it's working fine.
I suspect ..might be timeouts to reach the server ?

**Comment by stefan-niedermann** [comment] 2021-07-19 14:33
Not exactly timeouts, the error message would probably be different... keep an eye on it and tell me if it happens again - each hint about what you did before might be useful (list view -> edit note -> switch to preview etc., also each configuration change of the Nextcloud Android app or your server might give a hint)

**Comment by squintarelli** [comment] 2021-07-19 16:09
I didn't do anything special, just editing a note
will keep an eye on it and let you know

**Comment by stefan-niedermann** [comment] 2021-10-02 11:25
@squintarelli have you experienced this issue again since july or did you find a reliable way to reproduce the problem?

**Comment by squintarelli** [comment] 2021-10-03 19:01
no, did not experience it again.

**Comment by computersalat** [comment] 2021-10-03 19:25
Had same issue and did reinstall app.

Now I get synchronisation failed due to token mismatch (also see Screenshot) 

```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 4.19.110-perf+(2107310135)
OS API Level: 30
Device: OnePlus8
Manufacturer: OnePlus
Model (and Product): IN2013 (OnePlus8_EEA)

---

com.nextcloud.android.sso.exceptions.TokenMismatchException: Der Authentifizierungs-Token stimmt nicht überein oder dem Paketnamen fehlt die Berechtigung für diese Aktion
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.main.MainViewModel.lambda$synchronizeCapabilities$13$MainViewModel(MainViewModel.java:406)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainViewModel$Kr1O01KODRuj8fCWyoVh0ZkuW9I.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment] 2021-10-04 06:37
@computersalat Please clear the storage of *both* apps and reimport your account [as described in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error). If this does not help, feel free to open a new issue (filling the complete issue template) - your issue is unrelated to this issue.

@squintarelli This was most likely some kind of weird constellation on your device and maybe with the files app itself. Since i have no idea how one should debug such a scenario (or what the scenario even was) plus there is an easy workaround, I'll close this issue as not reproducible. Thanks for your report and feel free to open a new issue if you have new insights :slightly_smiling_face:

**Closed by stefan-niedermann** 2021-10-04 06:37 UTC
