### ISSUE TITLE
Changing DataFlow

### ISSUE THREAD

**Issue by HeaDBanGer84** [stefan-niedermann/nextcloud-notes#61] opened 2016-01-22 15:25 UTC
I would recommend to sepperate in app Dataflow from persistence and synchronisation. Persistence and synchronisation could be handled with a Service-class and the Internal Data Managment could handled only through the adapter which Binds with the Service. Ithink this should fix the Issues:
#39 and #55

What you think?

**Comment by stefan-niedermann** [comment] 2016-01-23 09:44
I would be fine with it. Sounds great.
But how do you think, this affects #39? I think the performance issue (i didn't notice it yet on my nexus 4) here is caused by bypass which parses the markdown on every note open.

**Comment by HeaDBanGer84** [comment] 2016-01-23 14:41
Latest Changes pushed on my repository on branch SyncService. Still needs some testing but I think its worth it.

**Comment by stefan-niedermann** [comment] 2016-10-26 09:37
@HeaDBanGer84 haven't heared from you for some time - is this still an issue you are actively working on?

**Comment by HeaDBanGer84** [comment] 2016-10-28 07:17
Sorry, no spare time. I follow the Project actively and will do some work when i'm able to. All things i tried ended with some sort of wired sync issues. I havent look at the current code but saw that korelstar changed some things. Perhaps on Chrismas Holliday I con start again.

**Comment by stefan-niedermann** [comment] 2017-01-20 08:55
I am closing this issue for now. Feel free to reopen it when you have enough spare time to start work on it again :)
Regards

**Closed by stefan-niedermann** 2017-01-20 08:55 UTC
Labels: Enhancement
