### ISSUE TITLE
Links with relative URLs

### ISSUE THREAD

**Issue by lenzls** [stefan-niedermann/nextcloud-notes#623] opened 2019-12-16 22:02 UTC
Hello,

imagine a note like
```
 1. [link!](https://www.example.com)
 2. [link!](example.com)
 3. [link!](56366)
```

### Behaviour nextclound notes webapp:
1. is a link to `https://www.example.com`
2. Is a relative link like `https://<nextcloud>/apps/notes/note/example.com`
3. Is a relative link like `https://<nextcloud>/apps/notes/note/56366`, which is a link to another note and allows me to link different notes with each other

### Behaviour nextclound notes android:
1. is a link to `https://www.example.com`
2. Is not interpreted as a link at all
3. Is not interpreted as a link at all

-----

I think it would be nice to also support some kind of local linkage between notes. I'm currently trying out to use the notes as kind of a wiki-like system.

And while doing that I stumbled over the issue above.

**Comment by stefan-niedermann** [comment] 2019-12-17 08:47
Hi,

i am open to implement this, but only if the server app will implement this too (we have to male sure that we both use the same linking system / uri scheme).

@korelstar what do you think about it?

Just for reference some discussions and an old PR: https://github.com/stefan-niedermann/nextcloud-notes/pull/202

**Comment by lenzls** [comment] 2019-12-17 18:13
@stefan-niedermann 
That's nice to hear!

Forgive me my ignorance, but doesn't the webapp already implement this?

As shown in the issue, when using relative urls in the webapp, the linking already works. 
The link `[link!](56366)` is rendered as `https://<nextcloud>/apps/notes/note/56366`. And when clicking this link, my browser correctly takes me to the linked note. 

Of course the android app needs to behave a little different, since linked pages are normally rendered in a browser and not in the nextcloud-notes application.

**Comment by stefan-niedermann** [comment] 2019-12-20 08:47
Indeed. The id is interpreted as a relative URL part which causes a click on it to jump directly to that note. Well then :) I think, one could grap out #202 and work on this base :)

**Comment by lenzls** [comment] 2019-12-20 17:03
I think I might give it a try.

But before I'd like to get the behaviour straight.

### proposal
#

**Comment by lenzls** [comment] 2019-12-20 17:16
I think I might give it a try. 

But before I'd like to get the behaviour straight.

## proposal

Given the following markdown examples

 1. `[link!](https://www.example.com)`
 2. `[link!](example.com)`
 3. `[link!](<id-of-existing-note>)`
 4. `[link!](<string-that-looks-like-an-id-but-there-is-no-such-note>)`

in view mode these snippets will be rendered as

 1. an actual hyperlink with text "link1" pointing to "https://www.example.com". If you click the link, your webbrowser opens the link
 2. will not be interpreted at all. It gets rendered as the string `[link!](example.com)`
 3. an hyperlink with text "link!" pointing to a note. If you click the link, the note will be opened in the nextcloud notes application
 4. will not be interpreted at all. It gets rendered as the string `[link!](<string-that-looks-like-an-id-but-there-is-no-such-note>)`

### notes

 - only case (3) behaves differently than the current implementation. The other cases are not effected.
 - case (2) and (4) behave differently than the webapp which tries to interpret them as relative links

### open questions

 - How do nextcloud note ids look in general? All my notes so far have ids that are natural numbers with 5 digits. Can there be more digits?


-----

Any remarks from you guys?

**Comment by korelstar** [comment] 2019-12-20 20:20
I'm fine with this approach. The ID is Nextcloud's file ID. It is an integer without any restrictions. So it could be 1 or more digits.

**Comment by stefan-niedermann** [comment] 2019-12-28 08:20
> I think I might give it a try.

I am looking forward to your PR 🚀 😃 

Your proposal looks very good to me. I think to keep the steps small, we should limit the scope to the easier use-case (3). Implementing a custom url scheme handler for opening notes from your browser via click is not needed for now.

**Comment by lenzls** [comment] 2019-12-28 14:25
Pull request is there, but I'm not sure if we can be satisfied with it :D

**Comment by stefan-niedermann** [comment] 2020-01-18 08:05
Merged! :tada: thank you :)

**Closed by stefan-niedermann** 2020-01-18 08:05 UTC
Labels: New Feature

**Comment by minimeee** [comment] 2020-01-25 15:33
Very nice! I really like this feature :+1:  But I've noticed one thing: when I open a linked note from another one (in the app) and then hit the "back" button, I don't get back to the note I came from (but to the notes list). Is this intended behaviour or are you planning to change / fix it?

**Comment by stefan-niedermann** [comment] 2020-01-25 15:54
Maybe @lenzls or you @minimeee want to create a PR for that? :wink:

**Comment by lenzls** [comment] 2020-01-25 16:13
Not not intended by me. I actually thought that the back button worked correctly.

I'll have a look to coming days.

Thanks for the hint :)

**Comment by lenzls** [comment] 2020-01-26 19:18
Indeed I could reproduce the issue. i opened a PR with a fix. You guys can have a look functional and technical.
