### ISSUE TITLE
Phone rotation wipes note

### ISSUE THREAD

**Issue by woodcarver76** [stefan-niedermann/nextcloud-notes#341] opened 2018-03-01 15:54 UTC
Changing the rotation (portrait/landscape) on my Oneplus 5T empties the entire note, and if I press Back it also wipes the synced copy on the server.

I'm guessing it doesn't affect all phones and installations, since someone else would have noticed. But I have made screenshots if anyone needs to analyze what happens.

**Comment by stefan-niedermann** [comment] 2018-03-02 06:01
Hi,

this is a duplicate of #301.

Which version do you use? v0.13.1 has the fix  and is currently rolling out at Play Store. So if you are still using v0.12.1 you should wait a few days, until you get the update and test again :)

Please reopen, if this still occurs with v0.13.1

Thank you :)

**Closed by stefan-niedermann** 2018-03-02 06:01 UTC
