### ISSUE TITLE
HTTP 500: `MultiKeyDecryptException`

### ISSUE THREAD

**Issue by NoomiPetrinen** [stefan-niedermann/nextcloud-notes#1572] opened 2022-08-27 11:33 UTC
**Expected behavior*
Since a few months, some notes cannot synchronize with nextcloud over dav.  The note however Is backd up in the cloud and available. But in the Note app on my phone, the content of these unsynchronizable files is this text: "Error: OCA\Encryption\Exceptions\MultiKeyDecryptException"

**Server**
 - Nextcloud version: 3.21.5
 - Nextcloud Notes version (server app): pro.woelkli.com 
 
In the following i copied the error log:
```
App Version: 3.2.3
App Version Code: 3002003
App Flavor: fdroid

Files App Version Code: 30210090

---

OS Version: 4.14.113-24700230(G715FNXXUADVG4)
OS API Level: 31
Device: xcoverpro
Manufacturer: samsung
Model (and Product): SM-G715FN (xcoverproxx)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.editNote(NotesClientV1.java:49)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalStateException: {"errorType":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)


com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.editNote(NotesClientV1.java:49)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalStateException: {"errorType":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)


com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.editNote(NotesClientV1.java:49)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalStateException: {"errorType":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)


com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.editNote(NotesClientV1.java:49)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalStateException: {"errorType":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)


com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.editNote(NotesClientV1.java:49)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalStateException: {"errorType":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)


com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.editNote(NotesClientV1.java:49)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalStateException: {"errorType":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)


com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 502
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:31)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html dir='ltr' lang='en'>
  <head>
    <meta http-equiv='Content-Type' content='text/html;charset=utf-8'/>
    <title>The website is under maintenance</title>
    <style>
      body {margin:0;font-family:arial,sans-serif;color:#8c8c8c;line-height:1.5em;text-align:left;}
      body, html {height:100%;}
      #top {position:absolute;top:0;left:0;width:100%;padding:0.5em 0;background-color:#111;box-shadow:#424242 1px 0 5px;}
      #inside {color:#f3f3f3;font-weight:bold;padding-right:1em;padding-left:1em;}
      #inside a {text-decoration:none;color:#f3f3f3;}
      #logo {float:left;display:inline-block;}
      #logo a, #logo img {vertical-align:middle;}
      #logo img {margin-right:0.5em;}
      #pnf {clear:both;display:block;overflow:auto;width:100%;min-height:100%;margin-bottom:-6em;background:url('https://woelkli.com/static-images/cow.jpg') 0 0/cover no-repeat transparent;}
      #pnf:after {display:block;height:8em;content:'';}
      #dialogue-outer {float:left;margin:8em 2em 7em 3em;padding:2em;width:40%;background-color:rgba(250, 250, 250, 0.5);-moz-border-radius:0.4em;-webkit-border-radius:0.4em;-ms-border-radius:0.4em;-o-border-radius:0.4em;border-radius: 0.4em;}
      #dialogue {padding:2em;background-color:#fafafa;-moz-border-radius:0.4em;-webkit-border-radius:0.4em;-ms-border-radius:0.4em;-o-border-radius:0.4em;border-radius:0.4em;-moz-box-shadow:0 2px 2px rgba(0, 0, 0, 0.196),0 1px 5px rgba(0, 0, 0, 0.196);-webkit-box-shadow:0 2px 2px rgba(0, 0, 0, 0.196),0 1px 5px rgba(0, 0, 0, 0.196);-ms-box-shadow:0 2px 2px rgba(0, 0, 0, 0.196),0 1px 5px rgba(0, 0, 0, 0.196);-o-box-shadow:0 2px 2px rgba(0, 0, 0, 0.196),0 1px 5px rgba(0, 0, 0, 0.196);box-shadow:0 2px 2px rgba(0, 0, 0, 0.196),0 1px 5px rgba(0, 0, 0, 0.196);}
      h1 {font-size:1.5em;font-weight:bold;text-shadow:rgba(255, 255, 255, 0.8) -1px -1px 2px, rgba(163, 163, 163, 0.8) 1px 1px 1px;}
      h2 {margin-top:1.5em;font-style:italic;}
      a {color: #275CA1;text-decoration: none;}
      #info {height:6em;margin:0 auto;background-color:#275ca1;-moz-box-shadow:#000 -1px 0 5px;-webkit-box-shadow:#000 -1px 0 5px;-ms-box-shadow:#000 -1px 0 5px;-o-box-shadow:#000 -1px 0 5px;box-shadow:#000 -1px 0 5px;}
      #info ul {margin:0 auto;padding-top:2.5em;text-align:center;}
      #info ul li {display:inline;padding-right:2em;}
      #info a {text-decoration:none;color:#f3f3f3;text-shadow:rgba(0, 57, 74, 0.804) 0 1px 1px,rgba(0, 57, 74, 0.196) 0 6px 5px,rgba(0, 57, 74, 0.102) 8px 0 8px;}
      #info a:hover {text-decoration:underline;}
      #footer #bl {display:block;padding-top:0.25em;padding-bottom:0.25em;background-color:#fff;}
      #footer #bl #cloud-software {display: inline-block;width: 33%;max-width: 33%;}
      #footer #bl #cloud-software a {text-align: left;}
      #footer #bl #cloud-software img {padding-left: 1em;width: 76px;height: 50px;}
      #footer #bl #host {display:inline-block;width: 33%;max-width: 33%;text-align: center;vertical-align: middle;}
      #footer #bl #host a {height: 39px;font-size: 1em;color: #666;}
      #footer #bl #host a:hover {text-decoration:none;}
      #footer #bl #ssl {display: inline-block;width: 33%;max-width: 33%;}
      #footer #bl #ssl a {float: right;text-align: right;}
      #footer #bl #ssl img {width: 169px;height: 39px;vertical-align: middle;}
    </style>
  </head>
  <body>
    <header id='header'>
      <div id='top'>
        <div id='inside'>
          <div id='logo'>
          <a href='/en'><img src='https://woelkli.com/static-images/woelkli.png' alt='woelkli logo'></a>
        </div>
      </div>
      </div>
    </header>
    <div id='pnf'>
      <div id='dialogue-outer'>
        <div id='dialogue'>
          <h1>The website is under maintenance</h1>
          <p>The website is under maintenance and will be back soon. Please check back again in a while.</p>
          <h2>In the meantime, you can:</h2>
          <ul>
            <li><a href='https://woelkli.com/en/signup'>Get a Cloud Storage account</a></li>
            <li><a href='https://woelkli.com/en/about'>Find out more about wölkli Cloud Storage</a></li>
            <li><a href='https://woelkli.com/en/faq'>Visit our frequently asked questions page</a></li>
            <li><a href='https://woelkli.com/en/help'>Read our how-to guides</a></li>
            <li><a href='https://pro.woelkli.com'>Sign in to your wölkli PRO account</a></li>
            <li><a href='https://cloud.woelkli.com'>Sign in to your wölkli FREE account</a></li>
          </ul>
        </div>
      </div>
    </div>
    <footer id='footer'>
      <nav id='info'>
        <ul>
          <li>
            <a href='https://woelkli.com/en/features'>Features</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/packages'>Packages</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/signup'>Sign up</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/upgrade'>Upgrade</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/donate'>Donate</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/onlyoffice'>ONLYOFFICE</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/collabora-online'>Colabora Online</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/downloads'>Downloads</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/help'>Help</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/faq'>FAQ</a>
          </li>
          <li>
            <a href='https://woelklimail.com/en/' target='_blank'>Encrypted e-mail</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/about'>About</a>
          </li>
          <li>
            <a href='https://woelkli.com/en/contact-us'>Contact</a>
          </li>
        </ul>
      </nav>
      <div id='bl'>
        <span id='cloud-software'>
          <a href='https://nextcloud.com/' target='_blank' rel='nofollow'>
            <img src='https://woelkli.com/static-images/nextcloud.png' alt='Nextcloud'>
          </a>
        </span>
        <span id='host'>
          <a href='https://oriented.net/' target='_blank'>© oriented.net LLC</a>
        </span>
        <span id='ssl'>
          <a href='https://letsencrypt.org/' target='_blank' rel='nofollow'>
            <img src='https://woelkli.com/static-images/letsencrypt.png' alt='SSL Secured'>
          </a>
        </span>
      </div>
    </footer>
  </body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)

```

**Comment by stefan-niedermann** [comment] 2022-08-27 12:24
Hmm, `HTTP 500` and `HTTP 502` hint on a server side issue rather than the Androids side.

> over dav

What do you mean with `over dav`? I don't understand that. The Notes Android app does not use `WebDAV` for synchronization.

>  The note

You earlier wrote `Some notes` - so what? One note? Multiple notes? Do you know which notes are causing this or was it just a guess?

> The website is under maintenance

Is the maintenance mode of your Nextcloud instan enabled or disabled? The HTTP response codes don't match the printed body...

- Did you already try to remove your account from the Notes Android app and readd it?
- Did you have a look at the server log files and search it for more detailled information?
- Did you have any recent changes in terms of end to end encryption? Maybe tried it or enabled it?

@korelstar do you have any idea here?

**Comment by korelstar** [comment] 2022-09-04 05:33
> @korelstar do you have any idea here?

I agree that this looks like a server error. Please have a look at your server's `nextcloud.log`. Maybe there is an error message with more information, at least the exact file names should be shown. `OCA\Encryption\Exceptions\MultiKeyDecryptException` gives a hint to server-side encryption. It's likely that there is a problem with that encryption. Do you are able to read those files (that are mentioned in `nextcloud.log`) using the Nextcloud files app?

**Comment by stefan-niedermann** [comment] 2023-01-12 10:27
Closing due to missing feedback. Please feel free to open a new issue in the [repository of the Notes server app](https://github.com/nextcloud/notes/issues/new?assignees=&labels=bug%2C+need+to+reproduce&template=bug_report.md&title=) given this is an issue of the Notes server app rather than the Notes Android app.

**Closed by stefan-niedermann** 2023-01-12 10:27 UTC
