### ISSUE TITLE
report a sync problem in android

### ISSUE THREAD

**Issue by TangdizhiH** [stefan-niedermann/nextcloud-notes#930] opened 2020-08-03 10:29 UTC
App cannot sync when I'm using my proxy service, below are the reports
```
App Version: 2.16.7
App Version Code: 2016007
App Flavor: fdroid

Files App Version Code: 30120190

---

OS Version: 4.14.116(10.0.0.156C00)
OS API Level: 29
Device: HWBKL
Manufacturer: HUAWEI
Model (and Product): BKL-AL20 (BKL-AL20)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Read error: ssl=0x7270053e88: I/O error during system call, Software caused connection abort
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:31)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

**Comment by stefan-niedermann** [comment] 2020-08-03 10:44
Hi, can you please reopen this issue in the SingleSignOn repository: https://github.com/nextcloud/Android-SingleSignOn/issues/new ?

This is nothing that should be handeled by 3rd party apps. Fo you have installed the Deck app and if so: Are you able to reproduce the issue there?

**Comment by ECquadrat** [comment] 2020-08-12 20:06
Seems to be the same on my device with Android 9. Changed my phone a week ago from Aquarius X5 Plus with Android 7.1 to this LG device.
Regards Marc

```
App Version: 2.16.7
App Version Code: 2016007
App Flavor: fdroid

Files App Version Code: 30120190

---

OS Version: 4.14.83-perf(201471648a712)
OS API Level: 28
Device: betalm
Manufacturer: LGE
Model (and Product): LM-G810 (betalm_e)

---

com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.putNote(NotesClientV02.java:40)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.editNote(NotesClientV02.java:48)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.putNote(NotesClientV02.java:40)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.editNote(NotesClientV02.java:48)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.putNote(NotesClientV02.java:40)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.editNote(NotesClientV02.java:48)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.putNote(NotesClientV02.java:40)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.editNote(NotesClientV02.java:48)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.deleteNote(NotesClientV02.java:52)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:393)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.putNote(NotesClientV02.java:40)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.createNote(NotesClientV02.java:44)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:384)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.getNotes(NotesClientV02.java:31)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by stefan-niedermann** [comment] 2020-08-12 20:45
@ECquadrat seems to be a different error message ans a different cause. Can you try to clear the storage of both apps, Nextcloud and Notes, as [described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error) and reimport your accounts?

**Comment by ECquadrat** [comment] 2020-08-12 21:14
Thanks for the really quick help! Yes, clearing the data and cache of NextCloud note app solved the problem! Had nothing to change in the NextCloud app itself.

Best regards, Marc


Am 12. August 2020 22:45:51 MESZ schrieb Niedermann IT-Dienstleistungen <notifications@github.com>:

**Comment by stefan-niedermann** [comment] 2020-08-13 06:58
Closing the original issue as it belongs to the [linked SSO library](https://github.com/stefan-niedermann/nextcloud-notes/issues/930#issuecomment-667951648). Also: Trying to clear storage of Nextcloud & Notes and reimporting might help.

**Closed by stefan-niedermann** 2020-08-13 06:58 UTC
Labels: Upstream :: SSO
