### ISSUE TITLE
Notes have disappeared (deleted)

### ISSUE THREAD

**Issue by axelsimon** [stefan-niedermann/nextcloud-notes#392] opened 2018-04-26 08:28 UTC
**Android version:** 5.1.1 CyanogenMod

**Device**: Sony Xperia Z3 Compact

**System language**: English (UK)

**App version:** e. g. v0.16.1

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. look for a note
  3. two of your notes have disappeared
  4. look in the nextcloud "activities" tracker, see that they were deleted several weeks ago (29 March, 3 March)
5. go to the nextcloud web interface to restore them from deleted items, discover they are not there

I also tried to delete a new note by swiping it away (reading about #238), but in this case it appears in the "deleted items".
So it looks like Nextcloud Notes deleted two notes. These were two important and/or useful notes I was working on, which makes it extra annoying. Not sure what else to add to be helpful here, sorry.

Thanks

**Comment by axelsimon** [comment] 2018-04-26 08:39
More info: after I deleted my new test note ("new note.txt") and found it in the "deleted items" view of Nextcloud, I did another test and uploaded and then deleted another file ("test.torrent") from the web interface.

When I went back to the deleted items view, "new note.txt" was no longer recoverable, but "test.torrent" was.

It would appear Notes is doing something to deleted files that purges them completely and prevents them from being recoverable. This is not good.

**Comment by stefan-niedermann** [comment] 2018-04-26 09:41
Hmm, the android app uses the server side API to delete notes, the app does not perform any delete operations ditectly, so if a note got deleted unrecoverable, you should open an issue at https://github.com/nextcloud/notes/issues

Of course the two notes should not have been deleted in the first place. Can you reproduce the behaviour and tell us what you did before the notes were gone in the app?

**Comment by natrius** [comment] 2018-05-27 16:15
I'm missing some notes from time to time too. What i found out, the file somehow got renamed to UPPERCASE.TXT from uppercase.txt (no clue how, the title is all the time "Uppercase") and it seems to break the app. If i rename it to UPPERCASE.txt via the normal Nextcloud app, the note is visible again. 
Maybe thats helpfull.

**Comment by korelstar** [comment] 2018-05-28 06:02
@natrius On which operating system does the server run and which file system do you use?

**Comment by axelsimon** [comment] 2018-05-28 10:03
First of all, sorry for the slow reply.

@stefan-niedermann :
> the app does not perform any delete operations ditectly, so if a note got deleted unrecoverable, you should open an issue at https://github.com/nextcloud/notes/issues

Good to hear the app doesn't delete anything directly but goes through the API. I'll open a bug report on the Nextcloud Notes app repo then.

> Can you reproduce the behaviour and tell us what you did before the notes were gone in the app?

Not really no, I just realised at some point I couldn't find these two notes I was 100% sure I'd created, and so I investigated to figure out what might have happened.

@korelstar :
> In this test scenario, after deleting the note ("new note.txt"): where did you used the notes app again?
>
> For me, the real problem seems to be that you can recover the latest deleted file, only. Please check if this is a general problem of your Nextcloud installation (i.e. create some files using the files app, delete them and try to recover them).

I did that test a month ago, sorry, I don't exactly recall how I proceeded. I'm not sure however what you mean when you say:
> where did you used the notes app again?

I will test your hypothesis of only being able to un-delete the last deleted item. Checking if “there is a general problem” with my Nextcloud install seems very vague however.

**Comment by korelstar** [comment] 2018-05-31 18:31
@axelsimon 
it wasn't clear to me, at which point you did used the notes app in your description. But for now, I'm looking forward to your undelete test.

@natrius 
Sorry, currently, I have no idea what the cause could be. The notes app doesn't change the file name to upper case. :confused:

**Comment by stefan-niedermann** [comment] 2018-08-26 11:49
Closing this because of missing feedback. Also i can not reproduce this behaviour. Please try again with current versions of the notes server and android app and feel free to reopen if you can provide detailled steps to reproduce.

**Closed by stefan-niedermann** 2018-08-26 11:49 UTC
Labels: sync
