### ISSUE TITLE
Preview mode is not rendering formatting markup or images

### ISSUE THREAD

**Issue by weierophinney** [stefan-niedermann/nextcloud-notes#612] opened 2019-11-18 16:19 UTC
**Android version:** 9.0 Pie

**Device**: Nokia 7.2 (2019)

**System language**: English (US)

**App version:** 1.0.1

**App source:** Google Play Store

**Steps to reproduce:**
  1. open the app
  2. click on a note known to contain image markup and formatting (headers, bold, italics)
  3. choose preview mode if not already in preview mode

I have notes that have markup such as the following:

```markdown
![some description](URL to image)

### This is a third-level header

**This is bold text.** _And this is italic._
```

When previewing directly within my Nextcloud instance or within QOwnNotes on the desktop, images display, and text formatted as headers or with bold or italics render. Within the Android Nextcloud Notes app, however:

- Images are not rendered. Instead, the image _markup_ is rendered.
- Headers are not rendered. Instead, the header _markup_ is rendered.
- Bold and italic text is not rendered. Instead the _markup_ for indicating bold and italic content is rendered.

Interestingly:

- Links are rendered
- Bullet points are rendered
- Numbered lists are rendered

**Comment by stefan-niedermann** [comment] 2019-11-19 13:41
Thank you for report. I am currently busy with implementing Single Sign On and multi account support. After finishing this work, i will work on #549 which is the cause of this issue and i help that it will solve this, too. Please be patient.

**Comment by weierophinney** [comment] 2019-11-19 14:23
Thanks for the follow-up and the link to the other issue; I'll track that one from here out!

**Comment by stefan-niedermann** [comment] 2019-12-29 22:01
I can confirm, that images are not rendered, indeed (though RxMarkdown should be capable of rendering images).

But bold, italic and headlines are rendered fine for me. Can you please double check and make a screen record for me?

**Comment by stefan-niedermann** [comment] 2020-01-12 19:16
@weierophinney please double check rendering of headers, bold and italic and provide a screenshot if this still doesn't work for you.

Like i said in my previous comment: Image 🖼  rendering issues are already known and confirmed.

**Comment by stefan-niedermann** [comment] 2020-01-25 06:20
Closing because of missing feedback.

**Closed by stefan-niedermann** 2020-01-25 06:20 UTC
Labels: Bug, Upstream :: Markdown
