### ISSUE TITLE
Allow to change title (filename) independent of first line

### ISSUE THREAD

**Issue by Bleuzen** [stefan-niedermann/nextcloud-notes#644] opened 2019-12-28 11:25 UTC
Hi, currently, the Title of a note is always the same as its first line.
But I don't want to have the title again in the textfile. It should be enough when the title is in the filename and can be edited independent of the notes content.

So please add an option to edit note titles without needing to change the first line in the note.
And don't repeat the title in the first line of the note to keep it clean.

As an example have a look at the Google Notes app.
In edit mode, there are two text fields. One for the title (should be the filename in our case) and one for the notes content (should be the textfiles content in our case).
This is much cleaner.

**Comment by Bleuzen** [comment] 2019-12-28 11:53
Ok, I found this now:
https://github.com/nextcloud/notes/issues/190

Seems to be so "by design".
Even if I (and others) think this is a really bad design.

Anyway, it is possible to change the filename (and so the title) without changing the first line in the notes content.
Maybe this app could do this for now to work around this bad design?

**Comment by stefan-niedermann** [comment] 2019-12-28 12:34
Hi,

since you have found the server-side issue already:

1. I *personally* have the opinion, that it is less distracting how it currently is, because i directly can write without having to think about any title for my note
2. **If the server app separates the title from the content, this android client will follow**

So best option for you is to up-vote the server issue and ideally create a Pull Request at the server repository. If you are no web developer, you can put a bounty on the issue to motivate the developers to implement this in their free time.

> Anyway, is it possible for this app to somehow workaround this bad design for now?

It might be possible, but i won't do it for several reasons:

- The still-used (#549 ) markdown lib is not maintained and each try to work around its bugs and limitations create a huge maintenance problem for us self.
- Feature comparison with the server app

Duplicate of #351, #190, #289, #55 and #24.

**Closed by stefan-niedermann** 2019-12-28 12:34 UTC
Labels: Duplicate, Server-App

**Comment by godfuture** [comment] 2020-05-20 19:55
Hi,
I am the guy from the server issue. I think as well that showing the information twice is not the best option. I would say if the first row is the title, why do we need a title? And the other way round. We could leave out the first row at all.

The server side does it this way: if the user specifies renames the note, the title won't be changed automatically anymore. Would this be a feasible solution for the Android app as well? Both teams would be happy with this...

**Comment by stefan-niedermann** [comment] 2020-05-20 20:19
Yes, as soon as we support API v1.0, the behavior will be the same as on the server.
