### ISSUE TITLE
ETIMEDOUT when opening the app

### ISSUE THREAD

**Issue by tobru** [stefan-niedermann/nextcloud-notes#1399] opened 2021-11-10 19:49 UTC
**Describe the bug**

Everytime (at least most of the time, not exactly everytime) when I open the app I get a message that synchronisation failed. A refresh later the sync happens properly without issues. The error doesn't really show up everytime I open the app, but most of the time. I couldn't really figure out under which conditions it happens though. And the error happens on multiple devices.

**To Reproduce**

1. Open the app
2. See the error message
3. Refresh
4. Error gone

**Expected behavior**

When I open the app, no error appears and sync happens properly.

**Screenshots**

No screenshots available.

**Smartphone (please complete the following information):**

 - Nextcloud Notes-Version (android app): 3.4.16
 - F-Droid or Play Store: F-Droid
 - Android-Version: LineageOS 18.1 / Android 11
 - Device: Sony Xperia XA2

**Server**
 - Nextcloud version: 22.2.0
 - Nextcloud Notes version (server app): 4.1.1

**Stacktrace**

```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30170190

---

OS Version: 4.4.205-g06e048269450(eng.root.20211108.201018)
OS API Level: 30
Device: H4413
Manufacturer: Sony
Model (and Product): H4413 (H4413)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to files.REDACTED.com/REDACTED (port 443) from /10.67.235.143 (port 49722) after 60000ms: isConnected failed: ETIMEDOUT (Connection timed out)
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to files.tobru.ch/185.95.218.4 (port 443) from /10.67.235.143 (port 49722) after 60000ms: isConnected failed: ETIMEDOUT (Connection timed out)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment] 2021-11-10 20:22
Hey, that's a duplicate of #1303 (even though your stacktrace looks different - i also considered this error type). Please see [this comment](https://github.com/stefan-niedermann/nextcloud-notes/issues/1303#issuecomment-951963749) for further information.

**Closed by stefan-niedermann** 2021-11-10 20:22 UTC
