### ISSUE TITLE
Vertical scrolls in the preview and edit modes don't match

### ISSUE THREAD

**Issue by HuidaeCho** [stefan-niedermann/nextcloud-notes#1158] opened 2021-04-16 05:47 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Opening a long note in the edit mode briefly shows the correct vertical location as shown in the preview, but once the text is rendered (Markdown source code with varying font sizes), the total height of the note grows and, in effect, the expected vertical location is pushed down and now I'm looking at some pages above the preview location.

**To Reproduce**
1. Create a vertically long note with many headers (`# section`)
2. In the preview mode, scroll to the bottom of the note
3. Start the edit mode
4. See how it is briefly shown with no formatting at the correct location, which is ok
5. Once the text is rendered and vertically grown (because of increased font size), the same line in step 4 is pushed down and goes out of the view

**Expected behavior**

Retains the same current view in both the preview and edit modes.

Calculate the scroll location *after* text is rendered in the edit mode to address this issue.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Note 10+

**Server**
 - Nextcloud version: 13.0.12
 - Nextcloud Notes version (server app): 2.5.1

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2021-04-16 06:45
You are right with the symptoms: As the text grows, it is more likely that the vertical offset is different between edit and preview mode.

Unfortunately i am not aware of a solution for the problem, because you are wrong about the assumed root cause:

The size of headers isn't the cause; the scroll position is *not* saved in the short time when the text is not rendered yet, but it is saved when you actually scrolled.

What is really causing this differences are for example:

- Missing backtick characters of code blocks (minus 2 lines per codeblock in preview mode)
- Shortened text by rendered links instead of visible URLs in preview mode
- Less line breaks in preview mode because the text is shorter without visible markdown punctuation (`test` is shorter than `**test**`)

Pull Requests or ideas how to solve this issue are welcome - I am not aware of any way, therefore closing it unresolved (and happily reopen it when somebody wants to or knows how to implement this) 🙁

**Closed by stefan-niedermann** 2021-04-16 06:45 UTC
