### ISSUE TITLE
Drag shadow dimensions must be positive

### ISSUE THREAD

**Issue by IngoBelka** [stefan-niedermann/nextcloud-notes#909] opened 2020-07-03 08:05 UTC
1. Go to a note with checkboxes
2. put your finger on a checkbox a longer time
3. app crashes

```
App Version: 2.16.3
App Version Code: 2016003
App Flavor: fdroid

Files App Version Code: 30120090

---

OS Version: 4.14.117-perf+(V11.0.5.0.QFJEUXM)
OS API Level: 29
Device: davinci
Manufacturer: Xiaomi
Model (and Product): Mi 9T (davinci_eea)

---

java.lang.IllegalStateException: Drag shadow dimensions must be positive
	at android.view.View.startDragAndDrop(View.java:25474)
	at android.widget.Editor.startDragAndDrop(Editor.java:1241)
	at android.widget.Editor.performLongClick(Editor.java:1267)
	at android.widget.TextView.performLongClick(TextView.java:12243)
	at android.view.View.performLongClick(View.java:7217)
	at android.view.View$CheckForLongPress.run(View.java:27377)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by stefan-niedermann** [comment] 2020-07-11 09:54
Hi @IngoBelka 

thank you for the bug report. Unfortunately i have troubles reproducing this crash.

- Does this happen with every note with checkboxes or can you reproduce this only with a special constellation?
- Are you able to provide a minimal sample note where the error is always reproducable?

**Comment by IngoBelka** [comment] 2020-07-26 10:55
Hello Stefen, sorry for the delay. This behaviour I saw with each note. I'm using the app for shopping lists. I did a deeper investigation, but I can't reproduce it with the current version of today. So, it seems you solved it yet.

**Comment by stefan-niedermann** [comment] 2020-07-26 10:57
I honestly doubt that it is completely solved because i believe the crash is within a used library (RxMarkdown).

Though this library is no longer maintained and we plan to replace it with an appropriate alternative in the long term. Therefore yes: Let's close it at least as "known issue" and "won't fix - with the old library".

Thabks for the report though and have fun with the app 🙂

**Closed by stefan-niedermann** 2020-07-26 10:57 UTC
Labels: Upstream :: Markdown
