### ISSUE TITLE
No synchronization when launching app via widget

### ISSUE THREAD

**Issue by haarp** [stefan-niedermann/nextcloud-notes#474] opened 2018-09-12 20:28 UTC
When opening the app normally via the launcher, it synchronizes the notes. When opening the app via the Note list widget (tapping on the title, no note is being opened directly) no synchronization is done.

**Comment by stefan-niedermann** [comment] 2019-12-29 22:19
Duplicate of #442

**Closed by stefan-niedermann** 2019-12-29 22:19 UTC
Labels: Duplicate, Widget :: All Notes, sync
