### ISSUE TITLE
Opening a note in view mode shows always a blank note

### ISSUE THREAD

**Issue by muchahagrande** [stefan-niedermann/nextcloud-notes#1065] opened 2021-02-14 19:46 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
Whe using the option to open a note in view mode. Every note that I open shows blank.
If I open it in edit mode, it shows fine.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Visualization mode'
3. Select 'Open in view mode'
4. Go back to notes list
5. Click on any note to open it
4. See a blank note

**Expected behavior**
The note should open in view mode as when you are editing it and switch to view mode.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.1.2
 - F-Droid or Play Store: F-Droid
 - Android-Version: 6.0.1
 - Device: Samsung SM-G903M (s5neolteub)

**Server**
 - Nextcloud version: 20.0.7
 - Nextcloud Notes version (server app): 3.5.1

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2021-02-20 18:35
Reproducible on an emulated Android 5 device. Unfortunately no stacktrace visible, further investigation needed...

**Comment by Cui-Yusong** [comment] 2021-04-25 13:20
Excuse me, has this problem been solved in the current version? @stefan-niedermann 
Because I don't have the "Visualization mode", "Open in view mode" in my nextCloud, I only have "Display mode for notes" and "Open in preview mode".
And is this problem only present under Android 6?
Thanks very much.

**Comment by muchahagrande** [comment] 2021-04-25 19:05
It has not been fixed yet.

**Comment by stefan-niedermann** [comment] 2021-04-25 19:38
@muchahagrande we had some pretty big changes in the `master` branch which have not been released yet, so there is a chance that this issue is already fixed in code - i will retest this.

> Because I don't have the "Visualization mode", "Open in view mode" in my nextCloud, I only have "Display mode for notes" and "Open in preview mode".

Yes, @muchahagrande was talking about `Display mode for notes`, it was probably just an imprecise translation.

> And is this problem only present under Android 6?

I haven't tested the issue with *each* available Android version, but i can confirm, that it is reproducible with Android 5 and 6 and that it did not happen on Android 10+.

**Comment by muchahagrande** [comment] 2021-04-25 20:11
Hi @stefan-niedermann. Thank you for your message.
Yes I was talking about "Display mode" for notes. It was a misunderstanding.

I have android 6. As soon as you release the changes in master branch I'll test and give an update.

Thank you.

**Comment by muchahagrande** [comment] 2021-04-28 22:24
Well, today I updated to Notes 3.40 on my Android 6 phone and I can confirm that the problem is solved.

Thank you

**Comment by stefan-niedermann** [comment] 2021-04-29 06:33
Thank you for the patience 🙂 Must have been accidently solved by the Room refactoring which was quite big and impacted many placed over the app.

Feel free to reopem if the issue occurs again, of course.

**Closed by stefan-niedermann** 2021-04-29 06:33 UTC
Labels: Bug
