### ISSUE TITLE
Checkboxes are bigger in preview mode when line contains '☑'-character

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#654] opened 2020-01-02 10:29 UTC
- [x] The color of the checkboxes is too dark in dark-mode (see screenshot below).
- [ ] On my smartphone (LineageOS 16, Android 9), the checkbox variants "unchecked" and "checked" have different sizes (see screenshot below). However, on my emulator with Android 8, everything is fine.

![Screenshot_20200101-142912_Notizen](https://user-images.githubusercontent.com/6277619/71642184-cdac4080-2ca7-11ea-82aa-ae628bce793d.png)

**Comment by stefan-niedermann** [comment] 2020-01-28 10:44
@korelstar can you attach the exact markdown you are using as a `.txt`-file or share a pastebin?

I also noticed this, but it happened only at some combinations of headlines, linebreaks and some other stuff - I was never able to reproduce the issue perfectly.

I think this is yet another issue of `RxMarkdown` and i am not sure whether we can workaround it or not.

**Comment by korelstar** [comment] 2020-01-31 21:44
It looks that this happens when there are some special unicode characters in the same line. Here is an example which is reproducable:
```
- [ ] ☑
- [ ] Test
```

But it's an edge-case, then. So maybe the time to fix it doesn't worth it.

**Comment by stefan-niedermann** [comment] 2020-01-31 21:52
Nice research. I could imagime that emoji support the font is changed (which could cause higher lines and therefore bigger checkboxes).

**Comment by stefan-niedermann** [comment] 2020-02-01 22:44
Well, i think there's not much we can do on our side. Though `RxMarkdown` seems to be abandoned, i opened an issue (at least for documentation purposes): https://github.com/yydcdut/RxMarkdown/issues/66

I will close this because we will switch the markdown lib or at least fork it (in this case we can rely on the bugs which are already reported and documented in the original repo) in the long term...

**Closed by stefan-niedermann** 2020-02-01 22:44 UTC
Labels: Bug, UX, Upstream :: Markdown
