### ISSUE TITLE
Open note from widget doesn't synchronize first, data loss possible

### ISSUE THREAD

**Issue by KopfKrieg** [stefan-niedermann/nextcloud-notes#442] opened 2018-08-12 14:43 UTC
If I open a note from the widget (I'm using a single note widget), and edit the note, changes made from another device might get overridden and therefore lost if not recovered from Nextcloud itself.

It would be better if:
 - Notes got synchronized in the background, therefore minimizing the risk of overriding notes because they get synchronized in an interval (every few hours, for example)
 - Or, if opened from a widget, the specific note should get synchronized first, and then it should be allowed to edit it

Otherwise, changes made from other devices might get overridden without noticing, resulting in (effective) data loss.

**Comment by dan0xii** [comment] 2018-09-05 11:51
How would we handle the situation where the app can't synchronise the note: Proceed as it does now and accept for the possibility of data loss or prevent the user from editing the note? I don't think the latter is very appealing.

I get the problem you're laying out, I'm just wondering how best to handle it. This discussion may be of interest which overlaps the problem you're having: #161.

**Comment by korelstar** [comment] 2018-09-06 04:45
Please have also a look on this issue, it's a comprehensive analysis: https://github.com/nextcloud/notes/issues/56

**Comment by KopfKrieg** [comment] 2018-09-11 14:30
> Proceed as it does now and accept for the possibility of data loss or prevent the user from editing the note? I don't think the latter is very appealing.

I'd say override the file on the server on the next sync (therefore allow editing), or ask the user how to proceed.

Or, maybe (in general), if the file on the server has changed and we changed a note locally, ask the user what to do or merge them if possible.

> Please have also a look on this issue, it's a comprehensive analysis: nextcloud/notes#56

Oh, nice. Thank you for that.

**Comment by sotpapathe** [comment] 2019-08-20 16:18
Until a proper strategy for concurrent note edits is found, it could be worthwhile to add a background sync at a configurable interval in the Android app. This way note overwriting will hopefully occur less frequently.

**Comment by stefan-niedermann** [comment] 2019-08-20 17:30
While i aggree this raises several other problems, e.g.:

- newer android versions will kill the background service (which already causes headache for non-play-service-dependend messengers like deltachat and telegram)

- massive battery drain

**Comment by Keho** [comment] 2019-11-25 12:04
Hi,
Is it possible in the mean time to just synchronise a note when opening it from a widget?
If the app can't synchronise the note, either proceed as it does currently or just print a message « can't synchronise ».
Current situation when opening from widget:

Sync\Server | Note wasn't changed | Note was changed
--------- | ---------- | ---------
Can't synchronise | No data loss | Data loss
Can synchronise | No data loss | Data loss

New situation:

Sync\Server | Note wasn't changed | Note was changed
--- | --- | ---
Can't synchronise | No data loss | Data loss
Can synchronise | No data loss | No data loss

Most of the time the app should be able to synchronise…

**Comment by stefan-niedermann** [comment] 2020-02-01 09:35
Background Sync has been implemented in v2.10.0 (on F-Droid available in a few days, on Play Store available on the Beta track).

On preview mode you can also pull down to refresh to make sure you have the current version.

This should lower the risc of overriding data.

Still: There is no real conflict handling yet. But this is basically a duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/161.

Therefore i will close this issue and we can work on **real** conflict handling im #161.

**Comment by stefan-niedermann** [comment] 2020-02-01 09:36
PS: For now you will have to manually enable the background sync in the settings (in a future version background syn will be enabled by default).

**Closed by stefan-niedermann** 2020-02-01 09:35 UTC
Labels: Sync, Widget :: All Notes, Widget :: Single Note

**Comment by MiMoHo** [comment] 2025-06-02 16:55
I am experiencing loss of data due to missing synchronization frequently which makes Nextcloud Notes unreliable when being used across multiple devices. Background synchronization does not solve this, perhaps as when editing a note offline and switching off flight mode, it doesn't check for newer versions made externally before syncing its own changes _additionally_.
There was a [fix](https://github.com/nextcloud/notes/pull/692) implemented with the help of ETags in 2021, however, the author [pointed out](https://github.com/nextcloud/notes/issues/56#issuecomment-797507800) that "Third-party clients have to implement their part". Can someone do this work or at least re-open this issue? 🙏 @stefan-niedermann
