### ISSUE TITLE
Crash on start after upgrade to 2.10.1

### ISSUE THREAD

**Issue by pSub** [stefan-niedermann/nextcloud-notes#732] opened 2020-02-18 15:21 UTC
**Describe the bug**
Crash on start after upgrade to 2.10.1

**To Reproduce**
1. Start the app
3. See error

**Expected behavior**
App starts without any error.

**Server**
 - Nextcloud-Version: 
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: 

**Smartphone (please complete the following information):**
 - F-Droid
App Version: 2.10.1
App Version Code: 79
Files App Version Code: 30100190
OS Version: 3.4.0(102.0.1920)
OS API Level: 19
Device: KC-S701
Model (and Product): KC-S701 (KC-S701)

**Stacktrace**
```
android.view.InflateException: Binary XML file line #109: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at it.niedermann.owncloud.notes.model.ItemAdapter.onCreateViewHolder(ItemAdapter.java:79)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16511)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:641)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:16511)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2309)
	at android.view.View.measure(View.java:16511)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1952)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1149)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1331)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1036)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5713)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5050)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/border.xml from drawable resource ID #0x7f080060
	at android.content.res.Resources.loadDrawable(Resources.java:2112)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.view.View.<init>(View.java:3565)
	at android.widget.TextView.<init>(TextView.java:641)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	... 71 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:327)
	at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:970)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
	at android.content.res.Resources.loadDrawable(Resources.java:2108)
	... 81 more
```

**Comment by stefan-niedermann** [comment] 2020-02-18 15:27
Fixed in `v2.10.2` - duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/730

Thank you for reporting.

**Closed by stefan-niedermann** 2020-02-18 15:27 UTC

**Comment by pSub** [comment] 2020-02-18 15:41
Uh, don't know how I missed that ticket. Maybe I shouldn't create issues on my phone. Sorry.

**Comment by stefan-niedermann** [comment] 2020-02-18 15:43
Absolutely no problem 🙂
