### ISSUE TITLE
Note get lost when the screen rotate 

### ISSUE THREAD

**Issue by Happyfeet01** [stefan-niedermann/nextcloud-notes#319] opened 2018-02-03 19:38 UTC
Hello,

When I write an note on my android Device and then I rotate the screen, the text get lost..

Nextcloud 12.0.5 and 13.0.0 RC4
Android 8.0

**Comment by korelstar** [comment] 2018-02-04 10:38
Duplicate of #301 . Please provide your information in that issue.

**Closed by korelstar** 2018-02-04 10:38 UTC
Labels: Duplicate
