### ISSUE TITLE
(Check-)Lists are not continued on return

### ISSUE THREAD

**Issue by P1zz4br0etch3n** [stefan-niedermann/nextcloud-notes#1050] opened 2021-01-22 16:38 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
When I start a list e.g. by typing "- first entry" and press return to jump to a new line, I face an empty line instead of a line beginning with "- ". The same happens for checklists ("- [ ]").

**To Reproduce**
1. Open the App
2. Create a new note
3. Type "- anything"
4. Press return

**Expected behavior**
The new line should begin with "- "

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.1.0
 - F-Droid or Play Store: Play Store
 - Android-Version: 11
 - Device: Google Pixel 4

**Server**
 - Nextcloud version: 20.0.3
 - Nextcloud Notes version (server app): 4.0.2

**Comment by stefan-niedermann** [comment] 2021-01-22 16:43
Duplicate of #1040 will be fixed in `3.1.0`.

**Closed by stefan-niedermann** 2021-01-22 16:43 UTC
