### ISSUE TITLE
content can be seen even if app is locked

### ISSUE THREAD

**Issue by Cyanic76** [stefan-niedermann/nextcloud-notes#1245] opened 2021-06-02 06:40 UTC
App loads content before asking for fingerprint unlocking, allowing everyone to see few notes even if app is locked

![app](https://cdn.discordapp.com/attachments/807525317593268234/849537460257292308/Screenshot_20210602-083810.png)

i'm using nextcloud notes v3.4.4

**Comment by stefan-niedermann** [comment] 2021-06-02 06:49
Please use the 🔍 search function before opening new issues.

Duplicate of #927

**Closed by stefan-niedermann** 2021-06-02 06:49 UTC

**Comment by Cyanic76** [comment] 2021-06-02 07:03
OK, I'm sorry
