### ISSUE TITLE
Crash on opening the App

### ISSUE THREAD

**Issue by MarcFu** [stefan-niedermann/nextcloud-notes#823] opened 2020-05-10 14:46 UTC
Samsung Galaxy S9+
Deutsch
Android 10

```
App Version: 2.11.13
App Version Code: 2011013
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 4.9.118-18339721(G965FXXU8DTC5)
OS API Level: 29
Device: star2lte
Manufacturer: samsung
Model (and Product): SM-G965F (star2ltexx)

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.android.activity.NotesListViewActivity}: android.database.sqlite.SQLiteException: duplicate column name: API_VERSION (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE ACCOUNTS ADD COLUMN API_VERSION TEXT
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7857)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: android.database.sqlite.SQLiteException: duplicate column name: API_VERSION (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE ACCOUNTS ADD COLUMN API_VERSION TEXT
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1372)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:811)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2321)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
	at it.niedermann.owncloud.notes.persistence.AbstractNotesDatabase.onUpgrade(AbstractNotesDatabase.java:272)
	at it.niedermann.owncloud.notes.persistence.NotesDatabase.onUpgrade(NotesDatabase.java:52)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:493)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:415)
	at it.niedermann.owncloud.notes.persistence.NotesDatabase.getAccounts(NotesDatabase.java:674)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.setupHeader(NotesListViewActivity.java:238)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.onCreate(NotesListViewActivity.java:153)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
	... 11 more

```

**Comment by stefan-niedermann** [comment] 2020-05-10 14:48
You can fix it by deleting the storage and reimport your account (Android settings -> Apps -> Notes -> Storage -> Delete Storage).

I guess it happened after updating the app? Which version did you use previously?

**Comment by MarcFu** [comment] 2020-05-10 18:05
Oh, good question. Try your advice and give Feedback.

**Comment by stefan-niedermann** [comment] 2020-05-11 09:53
This issue was caused by an update from an **very** old version (<= `1.0.1`) to a current version.
Only way to fix it if you got it once, is, as mentioned, to clear the storage.

The bug will be fixed in the next version (but only for people who did not receive it yet).

Thanks for you report!

**Closed by stefan-niedermann** 2020-05-11 09:53 UTC

**Comment by MarcFu** [comment] 2020-05-12 17:46
That fixed the problem.
Thanks
