### ISSUE TITLE
Note list widgit should create a note in it's respective category

### ISSUE THREAD

**Issue by joeySeal** [stefan-niedermann/nextcloud-notes#817] opened 2020-05-06 21:32 UTC
![Screenshot_20200506-172950](https://user-images.githubusercontent.com/2881557/81230374-5f61ec80-8fbf-11ea-8855-31c2d2775304.png)
It would be convenient if the plus icon created a note with the category already set to the category chosen when the widgit was created.

**Comment by stefan-niedermann** [comment] 2020-05-20 15:24
Will be fixed in the next version *after* `2.12.1`. It might be necessary to remove the list widget and add it again.

**Comment by stefan-niedermann** [comment] 2020-05-23 11:22
Ah, sorry, i unfortunately had to revert the changes because there was a bug. I will reopen this issue so we can keep tracking it.

I put arguments to the `newNoteI` intent, but the arguments seem to be `null`. Interesting thing is: If i put the same arguments to `templatePI` intent, they arrive successfully, even though i thought that the `templatePI` is only for clicking entries and not the + button.... :confused: :question: 

Maybe @dan0xii can have a look?

**Comment by dan0xii** [comment] 2020-05-23 12:28
I think what you're saying is correct from memory; will take a look.

**Comment by dan0xii** [comment] 2020-05-23 14:44
The cause was pendingIntent being re-used hence it appearing in templatePI and not newNoteI. I've just added unique request codes which should address it properly. I've not added them to the other two widgets because I don't foresee them being in conflict.

There's still a bug where you can't click the "+" icon on the NLW, close the app and then click it again on a different widget. You will always be presented with the original, stale note editor (and thus with the same category attached if applicable). Working on that now.

**Comment by stefan-niedermann** [comment] 2020-05-23 15:37
Just tested and merged your PR but this:

> > There's still a bug where you can't click the "+" icon on the NLW, close the app and then click it again on a different widget. You will always be presented with the original, stale note editor (and thus with the same category attached if applicable). Working on that now.

is still an issue, therefore i reopened the issue after merging your PR.

**Comment by dan0xii** [comment] 2020-05-23 15:42
Clicking the "+" gets dealt with as you'd expect but nothing happens at replace() when it gets here. Do you know why that might be?

https://github.com/stefan-niedermann/nextcloud-notes/blob/7729d27b0bfaab7ae9e65c90b6479d594b444c90/app/src/main/java/it/niedermann/owncloud/notes/android/activity/EditNoteActivity.java#L183

**Comment by stefan-niedermann** [comment] 2020-05-23 15:51
Yes i think its for setting / switching between edit mode and preview mode

**Closed** 2020-06-01 11:31 UTC
Labels: Enhancement, Widget :: Notes List

**Comment by stefan-niedermann** [comment] 2020-06-01 12:24
Solved by @dan0xii will be in release `2.12.2`. Thank you!
