### ISSUE TITLE
"Cancel" option in menu not really needed? Rather "Undo"?

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#467] opened 2018-09-01 19:20 UTC
Since we do autosave the note every few seconds, it seems that the "Cancel" option is a duplicate of the "Back" arrow in the top left?

Maybe we should rather introduce an "Undo" option? (Which then should possibly have "Redo" too.)

**Comment by korelstar** [comment] 2018-09-01 19:54
The "cancel" action is actually a "undo" action. Renaming it should be fine.

**Comment by jancborchardt** [comment] 2018-09-01 21:17
Just tried it and it doesn't undo the change I made. It basically just closes the note, returning to the list view – same as the back button.

For it to be proper undo, it of course has to undo and should also not close the note, so it can be edited further.

@stefan-niedermann what do you think?

**Comment by stefan-niedermann** [comment] 2019-12-17 09:09
The cancel option should undo all edits you have done since you have opened the notes.

I agree with @korelstar the naming should stay cancel rather than undo, bbecause it simply fits better here (undo what exactly? the last few words? everything?) while "cancel" clearly points at cancelling the current edit mode.

I am not able to reproduce the issue you mentioned, that cancelling is not working. I tried to type and call the action as fast as i can, but it did everytime exactly what i expected.

Therefire: closing. If one of you still can reproduce this issue, just open a new issue.

**Closed by stefan-niedermann** 2019-12-17 09:09 UTC
