### ISSUE TITLE
Crash making a note favourite

### ISSUE THREAD

**Issue by mbo42** [stefan-niedermann/nextcloud-notes#1116] opened 2021-04-07 23:30 UTC
**Describe the bug**
Crashed while I was clicking on the star next to a note to make it yellow.

**Expected behavior**
Not crashing

**To Reproduce**
1. Unstar note A
2. Star note B

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version  3.2.5
 - Play Store: 
 - Android-Version: 4.19.135-gdb4bfbca77cf
 - Device: Pixel 5 (redfin

**Server**
 - Nextcloud version:  20.0.8 - 20.0.8.1
 - Nextcloud Notes version (server app):  4.0.4

**Stacktrace**
Can't get

** Error dump from app **
App Version: 3.2.5
App Version Code: 3002005
App Flavor: play

Files App Version Code: 30150190

---

OS Version: 4.19.135-gdb4bfbca77cf-ab7081188(7119741)
OS API Level: 30
Device: redfin
Manufacturer: Google
Model (and Product): Pixel 5 (redfin)

---

java.lang.ClassCastException: it.niedermann.owncloud.notes.main.items.section.SectionItem cannot be cast to it.niedermann.owncloud.notes.shared.model.DBNote
	at it.niedermann.owncloud.notes.main.MainActivity.onNoteFavoriteClick(MainActivity.java:874)
	at it.niedermann.owncloud.notes.main.items.NoteViewHolder.lambda$bindFavorite$2$NoteViewHolder(NoteViewHolder.java:107)
	at it.niedermann.owncloud.notes.main.items.-$$Lambda$NoteViewHolder$rMM3HB1GZGgGy0PBr15pESOMH30.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by stefan-niedermann** [comment] 2021-04-08 06:21
Duplicate of #1023 - the old item in the list doesn't vanish and clicking on it will cause a not reliable state.
Will be fixed once #967 has been merged, thanks for the report, though!

**Closed by stefan-niedermann** 2021-04-08 06:21 UTC
