### ISSUE TITLE
Code visualization with inline code and code blocks buggy

### ISSUE THREAD

**Issue by HagenMorano** [stefan-niedermann/nextcloud-notes#1002] opened 2020-12-22 10:49 UTC
**Describe the bug**
There are basically two issues with the coloring and displaying of inline code and code blocks (markdown):

1. Inline Code (\`example`) gets cut in view mode when too long (see screenshot 2)
2. Color contrast of code blocks is very low on both view and edit mode (only tested on dark mode, see screenshot 1 & 2), also there are some dark ugly fragments in view mode (screenshot 2)
\`\`\`
example
\`\`\`

**To Reproduce**
1. Create a long `inline code`
2. Create a code block in dark mode

**Expected behavior**
Concerning inline code: Line should break
Concerning code block: Colors should be more contrasting

**Screenshots**
### Edit mode:
![Screenshot_2020-12-22-11-25-50-709_it niedermann owncloud notes](https://user-images.githubusercontent.com/25682450/102879485-1b3a3400-444a-11eb-900c-e12a4a57185a.jpg)
### View mode:
![Screenshot_2020-12-22-11-26-00-034_it niedermann owncloud notes](https://user-images.githubusercontent.com/25682450/102879492-1d03f780-444a-11eb-84e4-c3776702903a.jpg)

**Smartphone**
 - Nextcloud Notes-Version (android app): **2.17.1**
 - F-Droid or Play Store: **Play Store**
 - Android-Version: **10**
 - Device: **Xiaomi Mi Mix 2s**

**Server**
 - Nextcloud version: **20.0.3**
 - Nextcloud Notes version (server app): **4.0.1**

**Comment by stefan-niedermann** [comment] 2020-12-24 10:58
Uhmm 🤔 i can't reproduce this issue. On my device as well as on any emulator i use, the colors are correct.

Can you maybe tell me more about your Android settings like system wide dark mode, automatic night mode, display color adjustments and so on? Have you changed any default configuration of your Android system (to be clear: I am *not* talking about the App settings)?

**Comment by stefan-niedermann** [comment] 2020-12-24 10:58
cc @dan0xii

**Comment by HagenMorano** [comment] 2020-12-25 15:29
The only relevant setting I can see is the global dark mode. If set to `dark`, switching the theme in the application has no effect (`dark`,`light` and `system default` all result in a dark mode), switching global dark mode to `light` results in a desired behaviour: `light` and `system default` result in a light theme, `dark` results in a dark theme (expected behaviour).

Light theme looks good regarding colors but long inline codes are also cut.

There is one more UI relevant setting I can see in the d

**Comment by stefan-niedermann** [comment] 2020-12-25 15:51
> Maybe the problem gets resolved within #549 ?

I hope so, though the preview mode will still take some time to get implemented. But it would be very helpful if you could check the behavior of `2.18.1` (available at the Play Store Beta channel) to see whether this already fixes the issue at the editor. 🙂 

So long, stay well and merry X-Mas 🙂

**Comment by HagenMorano** [comment] 2020-12-25 16:00
Thanks for the quick reply! Just checked out beta version, but no changes concerning this issue unfortunately.

The issue is no show stopper as I am personally using backtick comments on laptop which is working quite good.

Merry Christmas to you too 🎄

**Comment by stefan-niedermann** [comment] 2020-12-25 17:00
Would you mind adding a screenshot of `v2.18.1` editor?

**Comment by HagenMorano** [comment] 2020-12-25 17:37
Sure - after restarting I just realized that edit mode now is indeed looking better - also font is now monospace. Like! See screenshots

![Screenshot_2020-12-25-18-34-27-432_it niedermann owncloud notes](https://user-images.githubusercontent.com/25682450/103139774-f6f78500-46df-11eb-9770-63f76f879cbb.jpg)
![Screenshot_2020-12-25-18-34-17-014_it niedermann owncloud notes](https://user-images.githubusercontent.com/25682450/103139775-f7901b80-46df-11eb-8539-6391e144a517.jpg)

**Comment by stefan-niedermann** [comment] 2021-01-05 14:08
Should be fixed in `v2.19.0` (available soon at the [Play Store beta channel](https://play.google.com/apps/testing/it.niedermann.owncloud.notes) and on F-Droid). Please reopen this issue in case it is still a problem with this version :slightly_smiling_face: 

And thanks for the helpful screenshots!

**Closed by stefan-niedermann** 2021-01-05 14:08 UTC
Labels: Dark Theme

**Comment by HagenMorano** [comment] 2021-01-07 07:30
Confirm :+1: Thanks a lot!

![1024-2048](https://user-images.githubusercontent.com/25682450/103864219-82025300-50c2-11eb-929b-745512b7bc9c.jpg)
![1024-2048 (1)](https://user-images.githubusercontent.com/25682450/103864220-83338000-50c2-11eb-91e2-8d0940fbca1f.jpg)
