### ISSUE TITLE
ArrayIndexOutOfBoundsException when clicking on Settings.

### ISSUE THREAD

**Issue by Emporea** [stefan-niedermann/nextcloud-notes#768] opened 2020-03-20 23:08 UTC
App Version: 2.11.3
App Version Code: 2011003
Files App Version Code: 30100190

---

OS Version: 4.9.118-17633310-SoLdieR9312(G960FXXS7DTB5)
OS API Level: 29
Device: starlte
Model (and Product): SM-G960F (starltexx)

---
```
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at androidx.preference.ListPreference.getEntry(ListPreference.java:213)
	at androidx.preference.ListPreference.getSummary(ListPreference.java:164)
	at androidx.preference.Preference.onBindViewHolder(Preference.java:510)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:418)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:47)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1058)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3652)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3112)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2169)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8933)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by stefan-niedermann** [comment] 2020-03-21 07:32
Hi @Emporea,

thank you for reporting the bug. A few questions:

- Where exactly did you click? The settings-item in the sidebar or at a specific settings entry (like darkmode or font size)?
- Can you reproduce the behaviour? Does it happen again and again or can you now modify settings without crash?

Thank you in advance

**Comment by Emporea** [comment] 2020-03-21 10:44
Hi,

the bug always appears when i hit Settings in the Sidebar / Navigation Drawer. I obviously rebooted, cleared the cache of the notes app and data but it doesn't help. The error still appears.

I just wiped & flashed a new version of my current rom and experiencing some other issues with other apps aswell, so maybe its on my side. But anyways, it's still a bug to catch.

**Comment by stefan-niedermann** [comment] 2020-03-21 22:31
Which ROM are you using? Did you install the app via F-Droid or Play Store?

To be honest, this looks much like a bug in your ROM and not in the app, since the stacktrace doesn't give any hint about the Notes code.

**Comment by stefan-niedermann** [comment] 2020-03-27 07:26
Hold on - I think it's a bug in the Notes app **and** i think i found the root cause.

@Emporea May i ask what language you are using on your phone?

**Comment by stefan-niedermann** [comment] 2020-03-27 08:52
Fixed with `2.11.6`. Please reopen if the issue still occurs with `2.11.6`.

**Comment by Emporea** [comment] 2020-03-27 13:55
> 
> 
> Hold on - I think it's a bug in the Notes app **and** i think i found the root cause.
> 
> @Emporea May i ask what language you are using on your phone?

Thanks for having a look at it again. I am using this rom
`https://forum.xda-developers.com/galaxy-s9/samsung-galaxy-s9--s9-cross-device-development/rom-u1arc5-devbase-v5-2-t3764822`

The current language of my phone is English (UK). Due to the fact that I use F-Droid for Nextcloud Apps it will take a while until I am able to update. But thanks.

**Comment by flocke** [comment] 2020-04-07 19:09
This happened to me again after todays update to 2.11.7 (F-Droid). It used to happen as well with 2.11.3 but was then fixed in 2.11.6 and is now happening again.

**Comment by stefan-niedermann** [comment] 2020-04-07 19:14
Will have a look as soon as possible.

**Comment by stefan-niedermann** [comment] 2020-04-08 08:22
Yep, the same error. Will be fixed in Version `2.11.8`. You can temporarily switch to your language to `en-US` to workaround the issue if it's urgent to change a setting until `2.11.8` has been rolled out.

---

:sparkles: summoning translation master @rakekniven :sparkles: 

@rakekniven i have some troubles here regarding transifex: There are some `<string-array>`s at the bottom of the `strings.xml`-file. It is important that either **none** or **all** string of those array-entires are translated. If **some** values are translated, this will lead to a crash for those languages as soon as one opens the settings.

I fixed it manually using Google Translator in this commit: https://github.com/stefan-niedermann/nextcloud-notes/commit/afa6355448adc457cac13a9026906474ae7d80a3 but all changes were overridden again.

Can you please re-add them in Transifex directly? Or do you have any other ideas how we could handle them?

Thank you in advance

**Comment by rakekniven** [comment] 2020-04-08 17:07
> ✨ summoning translation master @rakekniven ✨

It works ! Thank you :-)

> Can you please re-add them in Transifex directly? 

Just did that for strings referrenced in your commit

> Or do you have any other ideas how we could handle them?

Unfortunately not :-(

**Comment by stefan-niedermann** [comment] 2020-04-09 17:05
Yeah, i expected androidx fragments to handle this... i will dig into this and set a reminder to check the translations before every release.

Thanks for the help though.

**Closed by stefan-niedermann** 2020-04-09 17:05 UTC
Labels: Bug, Store :: F-Droid, Store :: Play Store
