### ISSUE TITLE
synchronization error

### ISSUE THREAD

**Issue by IngoBelka** [stefan-niedermann/nextcloud-notes#1132] opened 2021-04-12 17:29 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.9.148(9.1.0.335C432)
OS API Level: 28
Device: HWSHT
Manufacturer: HUAWEI
Model (and Product): SHT-W09 (SHT-W09)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
	at it.niedermann.owncloud.notes.persistence.n.h(Unknown Source:73)
	at it.niedermann.owncloud.notes.persistence.n.c(Unknown Source:23)
	at it.niedermann.owncloud.notes.persistence.k$c.h(Unknown Source:214)
	at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:14)
	at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)


b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
	at it.niedermann.owncloud.notes.persistence.n.e(Unknown Source:24)
	at it.niedermann.owncloud.notes.persistence.k$c.g(Unknown Source:64)
	at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:24)
	at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

```

**To Reproduce**
1. start the app
2. choose a note
3. get the error message

**Expected behavior**

synchronization

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: F-Droid
 - Android-Version: 9. 1
 - Device: HUAWEI MediaPad M5

**Server**
 - Nextcloud version: 20.0.2
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**

**Comment by EtienneM** [comment] 2021-04-12 17:45
I face the same issue. I install the Nextcloud Notes app from F-Droid. I tried to downgrade with the version 3.2.5 and it works. The latest (3.3.0) raises the above-mentioned sync error.

**Comment by EtienneM** [comment] 2021-04-12 17:45
Oh duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/1128 (cf. https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516).

**Comment by IngoBelka** [comment] 2021-04-12 18:00
Duplicate

**Closed** 2021-04-12 18:00 UTC
