### ISSUE TITLE
Open keyboard for typing default folder in Account settings

### ISSUE THREAD

**Issue by bvn13** [stefan-niedermann/nextcloud-notes#1602] opened 2022-11-04 09:24 UTC
Version 3.6.0
Since 3.4.0 at least.

When in account settings, in dialog for default folder opened. Tapping on text input does not open keyboard. 
User is unable to type default folder. It is possible to copy(somewhere) and paste it here only.

Device: honor 20 pro.

**Comment by stefan-niedermann** [comment] 2022-11-04 09:30
Duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/916#issuecomment-1001071467
Workaround: Copy & Paste until it has been fixed

**Closed by stefan-niedermann** 2022-11-04 09:30 UTC
