### ISSUE TITLE
Preview in the main part

### ISSUE THREAD

**Issue by talesam** [stefan-niedermann/nextcloud-notes#1219] opened 2021-05-16 17:23 UTC
When the notes is opened, the information appears in editing mode, both in list and in grid, and this makes it difficult to read the information. I believe that the editing mode should be used only for editing, so opening in preview mode would be very interesting. This view mode is only used when opening a note - if defined for that - but in grid mode, before opening a note, everything is in edit mode and is bad to view.

**Comment by stefan-niedermann** [comment] 2021-05-16 18:47
Hey @talesam 

yeah, i totally agree.

However, this is basically a duplicate of #924 - in short: We had it, render performance was horrible, we removed it on purpose.

We have a few ideas about how to improve the render speed, but none of the ideas are good enough for scrolling, especially on cheaper or older devices.

Closing this as it's not on our roadmap as long as we don't have a scalable solution which allows us to implement this in a technologically and architecturally way that is maintainable for a long time - sorry.

**Closed by stefan-niedermann** 2021-05-16 18:47 UTC
Labels: Enhancement
