### ISSUE TITLE
Detect missing `Notes` app on server when importing an account

### ISSUE THREAD

**Issue by JonasBernard** [stefan-niedermann/nextcloud-notes#1475] opened 2022-02-28 09:30 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
If you install the Android App for Nextcloud Notes and select a Nextcloud Account on a server that hasn't got the required notes extension installed, you do not get a warning. The app just stays on the "loading" screen forever.

**To Reproduce**
- Install a Nextcloud Server and create a new user
- Get the official Android Client and log in to that server and user
- Get this app (Nextcloud Notes) and open it
- From the automatically shown menu, select that account from above

**Expected behavior**
There should be a warning displayed that calls the user to install the Notes extension on the server.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.18
 - F-Droid or Play Store: F-Droid
 - Android-Version: 9
 - Device: Samsung (Galaxy A8)

**Server**
 - Nextcloud version: 22.2.3
 - Nextcloud Notes version (server app): n.a.

**Comment by stefan-niedermann** [comment] 2022-03-24 18:49
Yup, I found the cause of the issue (actually we are detecting a missing `Notes` app already, but there is a bug since some time).

I already have a fix for this issue locally and will publish it soon.

**Comment by stefan-niedermann** [comment] 2022-03-25 12:12
Will be fixed in `3.4.19`

**Closed** 2022-03-25 12:12 UTC
