### ISSUE TITLE
Colored Notes

### ISSUE THREAD

**Issue by Saphar** [stefan-niedermann/nextcloud-notes#1035] opened 2021-01-10 11:26 UTC
Would it be difficult to implement colors for the notes?

**Comment by stefan-niedermann** [comment] 2021-01-10 11:42
Please use the search function before opening new issues.

Duplicate of #434 and #356. Corresponding issue in the server repository: nextcloud/notes/issues/10

**Closed by stefan-niedermann** 2021-01-10 11:42 UTC
