### ISSUE TITLE
Search results: sort matches in title above matches in full text

### ISSUE THREAD

**Issue by csrichter** [stefan-niedermann/nextcloud-notes#483] opened 2018-09-21 09:13 UTC
Sometimes, when i search for a note, where i know the title, it takes a long time to find it, because the title appears in other notes.

**Comment by stefan-niedermann** [comment] 2019-02-06 21:54
This is by design. Often one does not remember the exact title, but remembers something from the text.

What else would you suggest?

**Comment by stefan-niedermann** [comment] 2019-10-14 10:20
Closing due missing feedback.

**Closed by stefan-niedermann** 2019-10-14 10:20 UTC
Labels: Discussion

**Comment by cdelledonne** [comment] 2023-05-07 15:32
I was also looking for some similar functionality and came across this issue.

What I think I would like to have is either of these two options implemented:

1. Simply sort notes whose title matches the search string on top of notes whose content matches the search string. Basically what the title of this issue suggests. If you think that some users might not like this behavior, it could be toggled with a setting.
2. Add some simple search filters, which only appear when the user is searching for something, which let the user decide what is being matched, i.e. title or full content or both.
