### ISSUE TITLE
Bug: Search results are shown for only 1 second

### ISSUE THREAD

**Issue by MathiasRenner** [stefan-niedermann/nextcloud-notes#580] opened 2019-08-26 22:16 UTC
When I type a search term, the search results are shown for about 1 second and then automatically disappear as if the search was canceled. 

This shows the use case twice, with two different search terms:

![ScreenRecord-nextcloud-notes-sea](https://user-images.githubusercontent.com/2377464/63727068-80cede00-c85f-11e9-80ec-d97728710734.gif)

As result, the search is not usable. Is this a known bug?

**Comment by stefan-niedermann** [comment] 2019-08-29 05:43
Actually no, i did not notice this behavior. Are you able to reproduce this issue on another device? I can't reproduce it, not on virtualachines nor with my real devices.

**Comment by MathiasRenner** [comment] 2019-09-04 09:28
@stefan-niedermann Hmm, interesting... I will test it on other devices soon. Thanks for your reply!

**Comment by stefan-niedermann** [comment] 2019-10-02 19:52
@MathiasRenner were you able to reproduce this on another device?

**Comment by MathiasRenner** [comment] 2019-10-03 11:16
@stefan-niedermann Stefan, I am sorry, unfortunately not yet... Do you have a chat group in place for your community, to ask for help? We only need someone with another Android phone.

**Comment by tribut** [comment] 2019-10-03 11:24
Cannot reproduce this bug (Samsung S8, Notes 0.27.1 installed from Google Play).

**Comment by MathiasRenner** [comment] 2019-10-03 11:25
@tribut Thank you! Hmm, very interesting....

**Comment by stefan-niedermann** [comment] 2019-10-03 13:14
You can reach me via Telegram (contact me via eMail at info@niedermann.it to get my phone number)

**Comment by stefan-niedermann** [comment] 2019-10-13 18:44
Closing because not reproducable. Feel free to reopen if anyone else has the same issue!

**Closed by stefan-niedermann** 2019-10-13 18:44 UTC

**Comment by MathiasRenner** [comment] 2019-11-05 22:25
In the forum, another person were not able to reproduce the bug. It's obviously a specific bug only for my environment. 
https://help.nextcloud.com/t/search-broken-in-my-nextcloud-notes-app-can-someone-reproduce/62652

**Comment by stefan-niedermann** [comment] 2019-11-06 06:13
There is no version `3.8.0` -  This is the current version of the files app. Maybe he did not try with notes all?
