### ISSUE TITLE
Copy/paste menu only appears over highlighted text sometimes

### ISSUE THREAD

**Issue by acloudadmin** [stefan-niedermann/nextcloud-notes#934] opened 2020-08-06 10:46 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

In the Android app, the copy/paste menu only appears over highlighted text sometimes

**To Reproduce**
1. Go to 'a note on android'
2. Click on 'long push on a word or sentence to highlight/select'
3. no menu pops up with  "Cut Copy Paste, etc, three dots." NOTE: This only happens some of the time. Sometimes the copy/paste menu pops up, but other times it doesn't

**Expected behavior**
Once text is highlighted/selected, a menu will ALWAYS pop up with "Cut Copy Paste, etc, three dots."

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.16.7
 - F-Droid or Play Store: f-droid
 - Android-Version: 10
 - Device: Pixel 3

**Server (please complete the following information):**
- Notes app version: 3.6.1
- Nextcloud version: 19.0.1
 

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2020-08-06 11:33
Hey there 👋

I didn't experience this yet on my devices, and i am not aware of someone else having this issue.

I would tend to say, it might be a local issue on your phone / with your ROM, but i am happy to keep the issue open for a while to see if someone else has it.

**Comment by acloudadmin** [comment] 2020-08-06 11:37
OK thanks.

Maybe you're right that it's an issue with my phone/ROM, but I do a lot of
cut/paste and I haven't experienced this problem in any other app.

-Andy

**Comment by stefan-niedermann** [comment] 2020-09-08 06:49
Are you able to reproduce this issue on another phone (of a friend e. g.)?

**Comment by KlausHuber** [comment] 2020-09-22 10:34
Same faulty behavior here.
**Client:**
- Nextcloud Notes Version: 2.16.7
- From F-Droid
- Android Version 10
- Device: Pixel 3a
Server:
- Notes App version: 3.6.4
- Nextcloud Version: 19.0.2

Force closing the App and starting it again also doesn't help. Unfortunately I can's say since when this issue happens here.
This is the logcat output when double-tapping a word:
```
09-22 12:27:43.337  3142  3142 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3160 
09-22 12:27:43.337  3142  3142 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1829 
09-22 12:27:43.340  3142  3142 I KeyboardViewUtil: KeyboardViewUtil.canAvoidFullscreenModeByReducingKeyboardHeight():87 can disable full screen mode by lowering keyboard. bodyHeight:1623 minBodyHeight:495
09-22 12:27:43.341  3142  3142 I GoogleInputMethodService: GoogleInputMethodService.onStartInputView():1946 
09-22 12:27:43.359  3189  4459 I System.out: LOGGGO: {757=1724, 758=10, 806=it.niedermann.owncloud.notes, 871=it.niedermann.owncloud.notes.edit.EditNoteActivity, 908=com.google.android.as, 1145=30, 1456=2021918648}
09-22 12:27:43.370  3142  3142 I KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():168 systemKeyboardHeightRatio:1.200000; userKeyboardHeightRatio:1.000000.
09-22 12:27:43.371  3142  3142 I AndroidIME: AbstractIme.onActivate():84 LatinIme.onActivate() : EditorInfo = Package = it.niedermann.owncloud.notes : Type = Text : Learning = Enable : Suggestion = Show : AutoCorrection = Enable : Microphone = Show : NoPersonalizedLearning = Disable : AutoStartVoiceInput = Disable, IncognitoMode = false
09-22 12:27:43.371  3142  3142 I Delight5Facilitator: Delight5Facilitator.initializeForIme():562 initializeForIme() : Locale = [de, en_US], layout = qwertz
09-22 12:27:43.371  3142  3142 I VoiceInputManagerWrapper: VoiceInputManagerWrapper.cancelShutdown():55 cancelShutdown()
09-22 12:27:43.371  3142  3142 I VoiceInputManagerWrapper: VoiceInputManagerWrapper.syncLanguagePacks():67 syncLanguagePacks()
09-22 12:27:43.371  3142  3142 I LatinIme: LatinIme.updateEnableInlineSuggestionsOnDecoderSideFlags():1157 inline flag updated to:false
09-22 12:27:43.371  3142 14530 I SpeechFactory: SpeechRecognitionFactory.maybeScheduleAutoPackDownloadForFallback():160 maybeScheduleAutoPackDownloadForFallback()
09-22 12:27:43.371  3142 14530 I FallbackOnDeviceRecognitionProvider: FallbackOnDeviceRecognitionProvider.maybeScheduleAutoPackDownload():195 maybeScheduleAutoPackDownload() for language tag de-DE
09-22 12:27:43.371  3142 14530 I FallbackOnDeviceRecognitionProvider: FallbackOnDeviceRecognitionProvider.maybeScheduleAutoPackDownload():195 maybeScheduleAutoPackDownload() for language tag en-US
09-22 12:27:43.373  3142  3142 I KeyboardWrapper: KeyboardWrapper.consumeEvent():281 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
09-22 12:27:43.376  3142  3142 I KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():66 leave 344 height for app when screen height:2088, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1623
09-22 12:27:43.379  3142  3142 I KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():66 leave 344 height for app when screen height:2088, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1623
09-22 12:27:43.379  3142  3142 I KeyboardViewUtil: KeyboardViewUtil.canAvoidFullscreenModeByReducingKeyboardHeight():87 can disable full screen mode by lowering keyboard. bodyHeight:1623 minBodyHeight:495
09-22 12:27:43.380  3142  3142 W KeyboardModeManager: KeyboardModeManager.setInputView():302 setInputView() : inputView = com.google.android.apps.inputmethod.libs.framework.core.InputView{e14996e V.E...... ......ID 0,0-1080,2022}
09-22 12:27:43.380  3142  3142 I ConversationToQueryExtension: ConversationToQueryExtension.isEnabledForHostApp():221 Conv2Query not enabled due to current app [it.niedermann.owncloud.notes] not in allowlist
09-22 12:27:43.380  3142  3142 I ConversationToQueryExtension: ConversationToQueryExtension.onActivate():131 onActivate() : Disabled by unsupported host app
09-22 12:27:43.381  3142  3142 I VoiceImeExtension: VoiceImeExtension.shouldStartVoiceInputAutomatically():341 No private IME option set to start voice input.
09-22 12:27:43.415  3142  3142 I KeyboardViewUtil: KeyboardViewUtil.canAvoidFullscreenModeByReducingKeyboardHeight():87 can disable full screen mode by lowering keyboard. bodyHeight:1623 minBodyHeight:495
09-22 12:27:43.415  3142  3142 I KeyboardViewUtil: KeyboardViewUtil.canAvoidFullscreenModeByReducingKeyboardHeight():87 can disable full screen mode by lowering keyboard. bodyHeight:1623 minBodyHeight:495
09-22 12:27:43.423  1404  4474 E InputDispatcher: Window handle Window{c388d15 u0 PopupWindow:a8264a7} has no registered input channel
09-22 12:27:43.499  6031  6031 D TextClassificationManager: Initialized SystemTextClassifier
09-22 12:27:43.499  6031  6031 W androidtc: TextClassifier called on main thread
09-22 12:27:43.502  3189  3189 I AiAiTextClassifier: onCreateTextClassificationSession = TextClassificationSessionId {cde635de-f3cd-4b66-9a0a-8db52dccecb6}
09-22 12:27:43.504  3189  3189 I AiAiTextClassifier: onCreateTextClassificationSession = TextClassificationSessionId {cde635de-f3cd-4b66-9a0a-8db52dccecb6}
09-22 12:27:43.512  3189  4464 I AiAiTextClassifier: Scheduling SmartSelectFL training.
09-22 12:27:43.513  3189  4464 I AiAiFed : [AiAi SmartSelect FL] *** disabled *** population=aiai/smartselect/prod
09-22 12:27:43.982  7844  9693 I Authzen : [DeviceStateSyncManager] The server is in sync with current state. Nothing to do
09-22 12:27:44.162   854  1193 I CHRE    : @ 349839.436: [ImuCal] [NanoSensorCal:GYRO_RPS] Offset | Temperature [C]: 0.000403, -0.000139, 0.000315 | 38.01
09-22 12:27:44.162   854  1193 I CHRE    : @ 349839.436: [ImuCal] [NanoSensorCal:GYRO_RPS] Temp Sensitivity: 0.000077, -0.000047, 0.000053
09-22 12:27:44.162   854  1193 I CHRE    : @ 349839.436: [ImuCal] [NanoSensorCal:GYRO_RPS] Temp Intercept: -0.002322, 0.001772, -0.001766
```

**Comment by Sonegide** [comment] 2021-02-10 18:20
Hello,
The copy/cut/paste menu never shows up for me.
I have this problem for months (sorry that it took me so long to raise it).

Phone: Xiaomi Mi 9T Pro
ROM: LineageOS 17 (Android 10)
Notes: 3.1.1 (from F-Droid)

**Comment by stefan-niedermann** [comment] 2021-02-10 18:27
@Sonegide please see #795 for *your* issue - it's not probably related to *this* issue.

**Comment by stefan-niedermann** [comment] 2021-03-16 21:48
@acloudadmin @KlausHuber are you experiencing the issues still with `v3.x.x`?

I haven't been able to reproduce the issue yet but i think it might have been related to the (in `v3.0.0` removed) library `RxMarkdown`).

**Comment by acloudadmin** [comment] 2021-03-16 22:00
Hi there,

Thanks for checking in. I'm using 3.2.2 and that issue seems to be
resolved. Thanks so much!

-Andy

**Comment by stefan-niedermann** [comment] 2021-03-16 22:12
Thanks for the quick feedback.

Then let's close this issue as `not reproducible`. Feel free of course, to open a new issue if it occurs again, so we can analyze it. 🙂

**Closed by stefan-niedermann** 2021-03-16 22:12 UTC
