### ISSUE TITLE
Feature request: change account without having to connect again

### ISSUE THREAD

**Issue by Zickfky** [stefan-niedermann/nextcloud-notes#583] opened 2019-08-30 08:40 UTC
Hello !
I was wondering if it was possible to add a feature which makes it possible to switch accounts quickly, and no need to connect each time, when you use 2 or more servers. This functionality is available in the Nextcloud android app.
Thank you !

**Comment by stefan-niedermann** [comment] 2019-08-30 08:51
Yeah, it's a duplicate of #171. Basically it is planned, but i am currently busy with the Nextcloud Deck app. We are using SingleSignOn there which enables us to quickly switch the account. I hope by creating the Deck app that i will learn enough to port those features to the Notes app. So please be patient, You also can create a PR of course if you want :)

Regards

**Closed by stefan-niedermann** 2019-08-30 08:51 UTC
