### ISSUE TITLE
Big inline-images are leading to crash on first sync

### ISSUE THREAD

**Issue by dev4223** [stefan-niedermann/nextcloud-notes#463] opened 2018-08-29 21:27 UTC
The app crashes while trying to login for the first time. Tried it on LG G4 and Samsung Tab S3.

**Comment by stefan-niedermann** [comment] 2018-08-30 08:07
Hi, can you be please more specific? Which version of the android app, the server app and nextcloud are you running? Do you see the Login form with url usernam and password? at which point das the app break? did you already enter some data?, ...

**Comment by dev4223** [comment] 2018-08-30 09:56
Hi, the App is version 0.21.0, nextcloud server is 13.0.5. I see the login form, fill my data (url gets a checkmark) and press LOGIN. Then after some time it crashes without any message.
I have already notes data in nextcloud, some 48 MB. I have exported it from Google Notes and converted the HTML to Markdown via pandoc. There are some images stored inline in these message, so they are very big, biggest is 17.2 MB. Maybe that's the point, I've thought.

**Comment by stefan-niedermann** [comment] 2018-08-30 12:47
what happens if you access the notes from the notes server side app? can you add only some small apps at the first step to see if a special (maybe big) note causes the error?

**Comment by dev4223** [comment] 2018-09-01 11:59
Hi, I've moved the biggest notes to another folder and now it works like charm. I have some notes with inline images under the notes and they work, too. So maybe just a size problem.
And as a feature request: How about to display inline images?

**Comment by korelstar** [comment] 2018-09-01 18:45
Is there an official syntax for image with inline-data?

**Comment by stefan-niedermann** [comment] 2019-02-09 08:48
@dev4223 can you provide a sample note which does not work for you? Because you said

> I have some notes with inline images under the notes and they work

So this seems to be not a general problem with inline-images.
But if we can not reproduce this behavior, we do not have any chance to fix this.

**Comment by stefan-niedermann** [comment] 2019-12-29 22:18
Closing due to missing feedback.

**Closed by stefan-niedermann** 2019-12-29 22:18 UTC
