### ISSUE TITLE
app crashes after adding enough text with markdown to a note

### ISSUE THREAD

**Issue by flat235** [stefan-niedermann/nextcloud-notes#1511] opened 2022-05-02 09:55 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

app crashes while adding some text with simple markdown (lists and headings) to a note.

the bug is reproducible for me with lengths 895 in the trace wach time, so there seems to be some limit (with markdown)

might be related to
https://github.com/stefan-niedermann/nextcloud-notes/issues/564
but seemed just different enough to me to at least report it

**To Reproduce**
1. open the app
2. click on existing note (contains only text and unordered lsts markdown)
3. add some text, use some simple markdown (headings and unordered lists)
4. at some point crash
5. the bug is reproducible for me with lengths 895 in the trace each time, so there seems to be some limit (with markdown)

**Expected behavior**

adding text with markdown works without crashing

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app):  3.4.19 (Version Code: 3004019)
 - F-Droid or Play Store: fdroid
 - Android-Version: 10 (see stack trace for more info)
 - Device: ONEPLUS A5000 (OnePlus5)

**Server**
 - Nextcloud version: 23.0.4
 - Nextcloud Notes version (server app): 4.3.1

**Stacktrace**
```
App Version: 3.4.19
App Version Code: 3004019
App Flavor: fdroid

Files App Version Code: 30190190

---

OS Version: 4.4.205-perf+(2010292059)
OS API Level: 29
Device: OnePlus5
Manufacturer: OnePlus
Model (and Product): ONEPLUS A5000 (OnePlus5)

---
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: setSpan (895 ... 899) ends beyond length 895
	at io.noties.markwon.editor.MarkwonEditorTextWatcher$WithPreRender$2$2.run(MarkwonEditorTextWatcher.java:168)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IndexOutOfBoundsException: setSpan (895 ... 899) ends beyond length 895
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1340)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:699)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:691)
	at io.noties.markwon.editor.MarkwonEditorImpl$RecordingSpannableStringBuilder.setSpan(MarkwonEditorImpl.java:203)
	at it.niedermann.android.markdown.markwon.handler.HeadingEditHandler.handleMarkdownSpan(HeadingEditHandler.java:69)
	at it.niedermann.android.markdown.markwon.handler.HeadingEditHandler.handleMarkdownSpan(HeadingEditHandler.java:14)
	at io.noties.markwon.editor.MarkwonEditor$SpansHandlerImpl.handle(MarkwonEditor.java:185)
	at io.noties.markwon.editor.MarkwonEditorImpl.process(MarkwonEditorImpl.java:85)
	at io.noties.markwon.editor.MarkwonEditorImpl.preRender(MarkwonEditorImpl.java:157)
	at io.noties.markwon.editor.MarkwonEditorTextWatcher$WithPreRender$2.run(MarkwonEditorTextWatcher.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment] 2022-05-02 10:04
Thanks for the report!

Actually it is not related #564 but it is a duplicate of https://github.com/stefan-niedermann/nextcloud-commons/issues/101 - the issue is not located in the Notes app itself, but in our upstream library.

Closing this issue therefore because it is tracked in the linked issue tracker.

**Closed by stefan-niedermann** 2022-05-02 10:04 UTC
