### ISSUE TITLE
Text area should cover whole screen

### ISSUE THREAD

**Issue by quthla** [stefan-niedermann/nextcloud-notes#538] opened 2019-02-13 17:58 UTC
On devices with large screen it's not easy to tap in the small text area when creating a new note. 

I think there's no disadvantage in making it always cover whole screen (like in other note apps)

**Comment by stefan-niedermann** [comment] 2019-04-10 12:37
Basically a duplicate of #331 but yes. See there for implementation problems. Pull Requests are welcome :)

**Comment by quthla** [comment] 2019-04-10 12:49
Couldn't you just make the edittext match_parent?

**Comment by stefan-niedermann** [comment] 2019-04-10 15:07
there was a issue with the scroling behavior as far i remember (i once tried to solve this some time ago)

**Closed** 2020-01-10 16:23 UTC
Labels: Good first issue
