### ISSUE TITLE
Remember last scrolling position per note

### ISSUE THREAD

**Issue by mfechner** [stefan-niedermann/nextcloud-notes#227] opened 2017-06-19 17:05 UTC
It would be really nice if the application could place the cursor at the end of the file.
This way you can continue to add information to a note without the need to scroll down manually the whole file.

**Comment by stefan-niedermann** [comment] 2017-06-19 20:32
I totally agree, the UX expert @jancborchardt suggested to place it at the beginning some time ago.

**Comment by jancborchardt** [comment] 2017-06-20 15:11
The issue is that this really depends on the type of note. For some notes it is best to put it at the end (if it’s a list you want to add things at the end of) for some it’s best to put it at the beginning (if you want to add more important things).

The best would be to _always_ remember where the cursor was last time you closed it, and jump to the same position. If there is no previous position, place it at the beginning like currently (cause that’s also the text you see in the preview of the list).

**Comment by mfechner** [comment] 2017-06-24 08:49
Normally text is written from top to down (at least in the western countries). So placing the cursor at the end at least match the read order. I see this as not the best solution, but it is the easiest to implement.
Maybe a configuration parameter in the app?

Second, and this is maybe the best solution, store the cursor position for each note and place it where it was before. But this would be more complicated to implement. Maybe we can split this into two improvement.

1. Add configuration parameter to select where to place the cursor be default (start/end)
2. Store location of cursor and place it on this position. If no position is existing, use definition from 1.

What do you think?

**Comment by jancborchardt** [comment] 2017-06-26 13:11
> Second, and this is maybe the best solution, store the cursor position for each note and place it where it was before.

That's exactly what I said above. ;) Additionally:

> If there is no previous position, place it at the beginning like currently (cause that’s also the text you see in the preview of the list).

That will also take care of your usecase without introducing an extra setting, since it will always use the cursor position from last time.

**Comment by stefan-niedermann** [comment] 2020-01-26 10:54
I basically agree that we want to restore the position of the last edit.

The problem is, that we decided to hide the keyboard when we open a note (because this allows an easier overview about the note).

So one has to tab into the textfield in either case (and implicitly sets the cursor while tapping)

Wouldn't it make more sense to save the **scrolling position**?

**Comment by jancborchardt** [comment] 2020-01-27 02:56
> Wouldn't it make more sense to save the **scrolling position**?

Yup, good point! :)

**Comment by stefan-niedermann** [comment] 2020-06-08 12:04
Will be fixed in `2.14.0`. Sneak preview:


![ezgif-3-80c395b41f4e](https://user-images.githubusercontent.com/4741199/84028386-e6283180-a990-11ea-944b-c4c6028d94c5.gif)

**Closed** 2020-06-08 12:05 UTC
Labels: UX

**Comment by jancborchardt** [comment] 2020-06-12 11:01
Wow, super smooth! :)
