### ISSUE TITLE
Accept custom certificates

### ISSUE THREAD

**Issue by theScrabi** [stefan-niedermann/nextcloud-notes#73] opened 2016-02-01 10:27 UTC
Hello,

can you please make, that the app is accepting custom certificates I can't install custom certificates since my cert installer on my phone is somehow broken.

**Comment by stefan-niedermann** [comment] 2016-02-01 10:32
Hmm, it would be better if you could fight the cause, not the symptoms. Have you tried to follow this Guide: https://coderwall.com/p/wv6fpq/add-self-signed-ssl-certificate-to-android-for-browsing

**Comment by theScrabi** [comment] 2016-02-01 12:18
No I know how to import android certificates xD, its just that the installer is broken due to removal of unnecessary bloatware that afterwards turned out important.

**Comment by theScrabi** [comment] 2016-02-01 12:21
Its not like you need to fix my errors, I want to switch to lets encrypt eniway, witch will fix that problem. It was just meant as an enhancement, because other owncloud apps also do it.

**Comment by sedrubal** [comment] 2016-02-01 14:24
I also think it's better to allow several certificates only for several apps and not for the entire system.

So :+1:

**Comment by theScrabi** [comment] 2016-02-02 11:09
Cool

**Comment by stefan-niedermann** [comment] 2016-02-02 13:51
Could you please explain me the benefit of allowing a certificate only for an app instead of the whole system? I don't get it. When *you* (as a person) trust a self-signed cert - why should not every of apps (which are all installed by *you*) trust this cert?

**Comment by sedrubal** [comment] 2016-02-02 14:48
Ok... maybe it's only a very small benefit... :D 

E.g. CACert: I don't want to genreally trust CACert but my owncloud runs with CACert and therefore I want only my owncloud apps to trust CACert.

But then I could only trust the server certificate of my owncloud system wide insteat of CACert root CA... ok...

So I don't know. But the App should at least give a feedback if the certificate is not trusted, but that is #72 I think...

**Comment by fxedel** [comment] 2016-02-02 19:18
I've just wanted to create this issue, then I saw that it's already there :smile:

Many owncloud installations are on local servers (like mine), so certificates always cause problems. The official owncloud app solves the problem by showing a dialog that the certificate isn't verified and asks if the user wants to continue. That would be my expected behavior: Simple, but the user still has the choice to disagree.

Installing certificates globally is much more complicated (e. g. I have to install Firefox if I only use stock android browser). IMO, there should at least be an error dialog with the message that the certificate isn't verified and a link to an instruction how to solve this.

**Comment by stefan-niedermann** [comment] 2016-02-02 19:22
> IMO, there should at least be an error dialog with the message that the certificate isn't verified and a link to an instruction how to solve this.

I definitely agree with this point. Okay. I will have a look into the source code of the ownCloud App and if this pop-up, @fxedel mentioned, can be adapted easily, i may do it. When i have time.

Pull-Requests based on master are welcome :)

**Comment by fxedel** [comment] 2016-02-02 19:25
:+1:

**Comment by stefan-niedermann** [comment] 2016-02-10 10:56
@David-Development are you interested in porting the self-signed-ssl trust mechanism from ownCloud News to ownCloud Notes? This would be a great help.

**Comment by theScrabi** [comment] 2016-02-10 11:07
I'd really like to help, but I loose enough time on my one project right now :/

**Comment by korelstar** [comment] 2016-11-25 18:40
The library [cert4android](https://gitlab.com/bitfireAT/cert4android) comes from the [DAVdroid](https://davdroid.bitfire.at/) project and seems to fit perfectly in this use case. Maybe, someone finds some time to integrate cert4android into the notes app?

**Comment by anonimou0** [comment] 2017-01-18 23:02
+1 =)

**Comment by sedrubal** [comment] 2017-01-19 00:36
I changed my mind: Cert4android might be a good choice but in times of letsencrypt this is nice 2 have but a less important issue, I think ;)

**Comment by anonimou0** [comment] 2017-01-19 00:48
@sedrubal , my ISP blocks port 80 and 443.. so, yeah, that's kind a deal breaker for me as i cant get a letsencrypt certificate

**Comment by gahujipo** [comment] 2017-05-30 14:19
+1

**Comment by korelstar** [comment] 2017-10-27 13:37
This feature was implemented by @schaarsc in #213 and released with v0.12.0. Thanks!

**Closed by korelstar** 2017-10-27 13:37 UTC
Labels: New Feature
