### ISSUE TITLE
Crash when copy/pasting

### ISSUE THREAD

**Issue by fillods** [stefan-niedermann/nextcloud-notes#1084] opened 2021-03-11 10:06 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
When doing a copy/paste between two notes, the app crashed.

**To Reproduce**
It happened once, I don't know how to reproduce it.

The copy/paste was done by selecting the text, long press on that text, choose "copy" from the contextual menu.
Then go to the destination note, long press where I wanted to paste the text, choose "paste" from the contextual menu.

**Expected behavior**
The text copied would have been pasted to the destination note, the app would be still running.

**Screenshots**
N/A

**Smartphone :**
 - Nextcloud Notes-Version (android app): 3.1.3
 - App Version Code: 3001003
 - F-Droid or Play Store: F-Droid
 - Android-Version: 8.0.0, 3.18.14-13997403-QB34852243(A320FLXXS9CTJ2), API Level: 26
 - Device: a3y17lte 
 - Model (and Product): Samsung Galaxy A3 2017, SM-A320FL
 - System language: French
 - Keyboard app : AnySoftKeyboard 4.0.1396
 
**Server**
 - Nextcloud version: (dunno how to get it, the Internet server is https://framagenda.org)
 - Nextcloud version (server app): 3.15.0

**Stacktrace**
```
java.lang.IndexOutOfBoundsException: 14, -5
at android.text.PackedIntVector.deleteAt(PackedIntVector.java:222)
at android.text.DynamicLayout.reflow(DynamicLayout.java:317)
at android.text.DynamicLayout.-wrap0(Unknown Source:0)
at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:750)
at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:779)
at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1292)
at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:647)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
at android.widget.TextView.paste(TextView.java:13343)
at android.widget.TextView.onTextContextMenuItem(TextView.java:12579)
at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4453)
at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:3068)
at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:107)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:172)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
at com.android.internal.view.FloatingActionMode.lambda$-com_android_internal_view_FloatingActionMode_5690(FloatingActionMode.java:134)
at com.android.internal.view.-$Lambda$IoKM3AcgDw3Ok5aFi0zlym2p3IA.$m$0(Unknown Source:4)
at com.android.internal.view.-$Lambda$IoKM3AcgDw3Ok5aFi0zlym2p3IA.onMenuItemClick(Unknown Source:0)
at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$3.onClick(FloatingToolbar.java:502)
at android.view.View.performClick(View.java:6897)
at android.view.View$PerformClick.run(View.java:26104)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```

**Comment by stefan-niedermann** [comment] 2021-03-11 10:10
Thank you for the detailled bug report. Are you able to reproduce the issue? Can you share the content of both notes, the start/end of your selection and the position where you tried to insert the text?

**Comment by fillods** [comment] 2021-03-11 10:25
Sorry no, I am not able to reproduce the issue, despite the fact I do copy/paste quite regularly since.
I cannot share the content of the notes because it is personal stuff.
All I can say is that the content is not too fancy. There is manly titles, sub-titles, enumeration items, some URL, french letters.
The biggest note is around 300 lines long.
IIRC, the copied text was less than 100 chars, not sure about other details. I don't know if I goofed something with the long press because the app crash after that.
If it happens again, next time I will write down all these details.

**Comment by stefan-niedermann** [comment] 2021-03-11 10:46
Okay, i will try to read something out of the stacktrace, but please don't be too disappointed if i will close this issue because i am not able to reproduce the issue and the stacktrace is a hint that this might be a bug in a deeper level (like Android stuff, custom ROM or so) - There's no hint to the Notes app or a used library as far as i can see yet.

**Comment by stefan-niedermann** [comment] 2021-03-16 18:14
Yeap. I have no idea :smile: 

Sorry, but i'll close this issue because

1. I am not able to reproduce it, neither are you
2. Noone else reported this issue. Given we have a quite big user base, i guess it would have been reported at least a second time if there was a general problem
3. The stacktrace (the error message) usually contains a line starting with `it.niedermann.nextcloud...` - since this doesn't contain this kind of trace, it looks at least for me like a bug in the Android ROM - probably a really really bad race condition which noone ever will be able to reproduce again.

I'd suggest you to reopen this issue if it occurs again **if** you are either able to reproduce it, give me more information (like exact contents of the notes - i know, not easy without kicking privacy in the ass, but this might help to reproduce it) or you get it on a different device (table or so).

Thanks again for the issue report and sorry that i don't have better news.

**Closed by stefan-niedermann** 2021-03-16 18:14 UTC

**Comment by fillods** [comment] 2021-03-18 10:19
That's fine with me. Thank you for taking the time to look at the traces. Should it occurs again in a reproducible manner, I'll reopen the issue.
Kudos for the great app!
