### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by felixendres** [stefan-niedermann/nextcloud-notes#1438] opened 2021-12-31 10:39 UTC
Hi,
I can reproducably crash the app with the following error, by putting a word on the last line, pressing enter, writing a minus (make a headline of the word) and press enter again.

```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30180190

---

OS Version: 3.10.84-perf-g99119bc(3761073091)
OS API Level: 25
Device: E5823
Manufacturer: Sony
Model (and Product): E5823 (E5823)

---

java.lang.IndexOutOfBoundsException: replace (169 ... 172) ends beyond length 171
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.deleteCustomText(AutoContinuationTextWatcher.java:78)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.afterTextChanged(AutoContinuationTextWatcher.java:60)
	at it.niedermann.android.markdown.markwon.textwatcher.LowerIndentionTextWatcher.afterTextChanged(LowerIndentionTextWatcher.java:49)
	at it.niedermann.android.markdown.markwon.textwatcher.SearchHighlightTextWatcher.afterTextChanged(SearchHighlightTextWatcher.java:61)
	at it.niedermann.android.markdown.markwon.textwatcher.CombinedTextWatcher.afterTextChanged(CombinedTextWatcher.java:47)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:8211)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10394)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:844)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:198)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:353)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by stefan-niedermann** [comment] 2021-12-31 10:44
Fixed in `3.4.18`
Duplicate of #1416, #1411, #1421, #1433, #1434

**Closed by stefan-niedermann** 2021-12-31 10:44 UTC
