### ISSUE TITLE
password before opening 

### ISSUE THREAD

**Issue by Trebor87** [stefan-niedermann/nextcloud-notes#592] opened 2019-09-30 15:24 UTC
hello

any chance of having a password / fingerprint control before opening Notes 

hope this is the right place for my question 

Trevor

**Comment by stefan-niedermann** [comment] 2019-10-01 06:25
Duplicate of #354

Pull Requests will be accepted, but my sparetime is currently very limited, so you ill have to be patient ;-)

**Closed by stefan-niedermann** 2019-10-01 06:25 UTC
