### ISSUE TITLE
table of contents based on the markdown headings

### ISSUE THREAD

**Issue by TimoMfr** [stefan-niedermann/nextcloud-notes#1022] opened 2021-01-05 16:24 UTC
Is it possible to show a hierarchical table of contents based on the markdown headings?
This could be opened via a button or a swipe menu and should be available in the edit mode and preview mode. A click on a heading jump to its position in the document.
The Goal is a better navigation and overview in larger documents.

it could look like this (all headings are clickable)
```
heading 1
    subheading 1
    subheading 2
heading 2
heading 3
    subheading 1
        sub-subheading 1
        sub-subheading 2
heading 4
```

**Comment by stefan-niedermann** [comment] 2021-01-05 16:28
Closing as duplicate of #401

**Closed by stefan-niedermann** 2021-01-05 16:28 UTC
Labels: Enhancement
