### ISSUE TITLE
Better grid view design

### ISSUE THREAD

**Issue by Bleuzen** [stefan-niedermann/nextcloud-notes#885] opened 2020-06-20 11:20 UTC
(from original issue https://github.com/stefan-niedermann/nextcloud-notes/issues/881)

But it can be improved:

- [x] **1) Use a little more spacing**
The upper note tiles look like they are glued to the search bar. A little more space to separate them would be nice.

- [ ] **2) Do not use different background color in grid view note tiles**
In dark mode. The main background color of the app is just fine. The light gray doesn't fit in well as background. Also it lowers the contrast and so makes the text a little harder to read.
My idea would be to use the light gray only as border

- [x] **3) Increase round corners on note tiles**
Just like the search bar. It is more round than the note tiles. This just adds inconsistency. Make the note tiles edges as round as the edges of the search bar so that they look the same.

Left: Current look
Right: Proposed look

| 1 | 2 |
| --- | --- |
| ![Screenshot_20200620-115013_flaw4](https://user-images.githubusercontent.com/12885163/85199588-f75a3200-b2f0-11ea-9672-e48933ed3b3b.jpg) | ![Screenshot_20200620-115013_flaw4-fix3](https://user-images.githubusercontent.com/12885163/85200028-58cfd000-b2f4-11ea-946d-494ffd3c11d7.png) |

**Comment by stefan-niedermann** [comment] 2020-06-20 11:30
Fully agree on 1. and 3. - both fixed now.

Don't agree to 2. 
This would make the view pretty two dimensional. But the cards are on another hierarchical level, therefore they need some elevation.
I propose to keep the different background, but to use the same background as the toolbar has. What do you think?

**Comment by Bleuzen** [comment] 2020-06-20 12:10
Guess this is a personal opinion thing. I prefer the flat style with the dark main background. But I would also be fine with the search bar background. The difference is not big and I think both look much better than current light gray. So go with whatever you like more.

Just for comparison:
| 1 | 2 |
| --- | --- |
| ![Screenshot_20200620-115013_flaw4-fix3](https://user-images.githubusercontent.com/12885163/85200028-58cfd000-b2f4-11ea-946d-494ffd3c11d7.png) | ![Screenshot_20200620-115013_flaw4-fix3_alt](https://user-images.githubusercontent.com/12885163/85201410-4e670380-b2ff-11ea-954f-59f39518140a.png) |

However, if you plan to use the lighter version (search bar background) I throw in a new idea. Do we need the border anymore if the card already has a lighter background?
Toolbar also does not have a border either. To make it consistent, I would prefer removing the light gray border in this case.

| 1 | 2 |
| --- | --- |
| ![Screenshot_20200620-115013_flaw4-fix3_alt](https://user-images.githubusercontent.com/12885163/85201439-9c7c0700-b2ff-11ea-8864-36bd3147145a.png) | ![Screenshot_20200620-115013_flaw4-fix3_alt2](https://user-images.githubusercontent.com/12885163/85201443-9ede6100-b2ff-11ea-82a7-abf04715fad7.png) |

What do you think?

**Comment by stefan-niedermann** [comment] 2020-06-20 12:13
i think "lol" because i just had the same idea and already hacked it in for a screenshot.

`#212121` for toolbar & card background in dark theme.

cc @thgoebel because he chose the color of the toolbar in dark mode

**Comment by thgoebel** [comment] 2020-06-20 12:36
I chose #1e1e1e because that what the [files app](https://github.com/nextcloud/android/blob/388301082dc9d255bf04f15f0d2e9e8c9a960529/src/main/res/values-night/colors.xml#L49) has. But #212121 look nice as well!

**Comment by stefan-niedermann** [comment] 2020-06-20 12:38
Thanks for your opinion, so let's go for `#212121` in this case as the use-case is slightly different with the cards in the Notes app :slightly_smiling_face:

**Closed** 2020-06-20 12:38 UTC
Labels: Dark Theme, Enhancement, UX

**Comment by Bleuzen** [comment] 2020-06-20 13:00
Thank you, this looks much better now :)

**Comment by Bleuzen** [comment] 2020-06-20 17:16
Just tested git master (https://github.com/stefan-niedermann/nextcloud-notes/commit/c6dec8542a6c41a42dc9dfa06fb0e495257b1673)
and this is how it looks on my device:

![Screenshot_20200620-190750](https://user-images.githubusercontent.com/12885163/85207648-76b82780-b32a-11ea-8dda-c3b7b64a6421.jpg)

There is now more space between the tiles. However, this was not my main concern.
The upper tiles are still like glued to the search bar, there is missing space.

**Comment by stefan-niedermann** [comment] 2020-06-20 17:19
Strange, cannot reproduce... Have you tried (just out of curiousity) to pull down 2 refresh?

**Comment by thgoebel** [comment] 2020-06-20 19:02
On my OnePlus 7 (OxygenOS 10) it looks the same as in that screenshot - little padding at the top of the recyclerview.

**Comment by Bleuzen** [comment] 2020-06-20 19:18
already scrolled up. This is with pull down:

![Screenshot_20200620-211705](https://user-images.githubusercontent.com/12885163/85209855-88ee9180-b33b-11ea-8c46-e76c15a28ffd.jpg)

**Comment by stefan-niedermann** [comment] 2020-06-20 19:25
@Bleuzen can you share details of the device (model & manufacturer) you are using? Maybe some weird constellation?

Since you already build the app version yourself: Can you also try it in an emulator?

**Comment by Bleuzen** [comment] 2020-06-20 19:28
I edited my last post to include the two devices I have tested it on and their Android version. Will also test in emulator...

**Comment by stefan-niedermann** [comment] 2020-06-20 19:31
Opened follow-up bug issue to track: https://github.com/stefan-niedermann/nextcloud-notes/issues/890
