### ISSUE TITLE
Sync failure after Undo of note

### ISSUE THREAD

**Issue by gadgetguy08** [stefan-niedermann/nextcloud-notes#1341] opened 2021-09-08 13:55 UTC
**Describe the bug**
After accidentally deleting a note (that had synced), I hit Undo and it appeared again in the list on the device.  However it disappeared from the NC server.  On one occasion there was an error Toast on the device, but usually there is a Note Restored Toast. Refreshing on the device does not help. 

[Workaround: if the note is modified on the device it will re-sync and re-appear on the server.]

**To Reproduce**
1. Create a note on device
2. Allow it to sync to server
3. Delete note on device
4. Click Undo on device to recover the note
5. Usually see a Note Restored Toast message on the device, but it is not on the server. [On one occasion received Error Toast message.]

**Expected behavior**
When recovering a note with Undo on the device, it should re-sync with server.

**Screenshots**

**Smartphone:**
 - Nextcloud Notes-Version (android app): 3.4.11
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Essential Phone

**Server**
 - Nextcloud version: 21.0.4
 - Nextcloud Notes version (server app): 4.1.1

**Stacktrace**  (occurred only one time, others appeared successful) 
**host name redacted**

```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 4.4.281-lineage-xxx
OS API Level: 30
Device: unknown
Manufacturer: unknown
Model (and Product): xxxx

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "mycloudaddresswhichisgood": No address associated with hostname
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "mycloudaddresswhichisgood": No address associated with hostname
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more
```

**Comment by stefan-niedermann** [comment] 2021-10-02 11:32
Thank you for the detailled issue description. This is a duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/1272 - in some scenarios the notes aren't flagged for sync and stay in the device therefore.

As you already learned yourself, one can change the content to force the note getting synchronized to the server (or just mark it as favorite for example).

The network stacktrace you posted is not directly related. Probably you had a bad connection at this point or switched between wifi and mobile data.

Closing as duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/1272

**Closed by stefan-niedermann** 2021-10-02 11:32 UTC
Labels: Bug
