### ISSUE TITLE
[Bug] Avatar isn't loading

### ISSUE THREAD

**Issue by Dvlnst** [stefan-niedermann/nextcloud-notes#717] opened 2020-02-03 23:12 UTC
![Screenshot_20200203-234553_Notes](https://user-images.githubusercontent.com/36289254/73698644-05ad0600-46e2-11ea-8f69-d087807608ef.jpg)

**Server:**
- **Nextcloud version:** 18.0.0
- **Nextcloud Files version:** 3.9.2
- **Nextcloud Notes version:** 3.1.2
- **PHP version:** 7.3

**Smartphone:**
 - **Nextcloud Notes-Version (android app):** 2.9.0
 - **Installed from:** F-Droid 
 - **Device:** Samsung Galaxy A70
 - **Android-Version:** 9

As you see on image, custom avatar is not loading. Sometimes when I open the app, default avatar disappears for some seconds but it comes again. It's working fine on Nextcloud Files.

Thank you for your awesome work,

Kind regards.

**Comment by stefan-niedermann** [comment] 2020-02-04 05:30
Yes, this one is a duplicate of https://github.com/stefan-niedermann/nextcloud-notes/issues/666

Current avatar only supports the most optimistic server setup you could imagine. As soon as it comes to special cases like self-signed certificates, it will currently roll back to the app icon.

Let's track this in https://github.com/stefan-niedermann/nextcloud-notes/issues/666 🙂

**Closed by stefan-niedermann** 2020-02-04 05:30 UTC
Labels: Duplicate

**Comment by stefan-niedermann** [comment] 2020-02-10 12:53
@Dvlnst could you please see this comment: https://github.com/stefan-niedermann/nextcloud-notes/issues/666#issuecomment-584107694 ?
